### PR TITLE
OpenAI new embedding models

### PR DESCRIPTION
**Pull request by hatianzhang**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by jerryjliu — APPROVED** [review]
nit: remove pip install notebook output

**Comment by ravi03071991** [comment]
@hatianzhang We probably have to include dimensions parameter to get different dimension embeddings. [reference](https://platform.openai.com/docs/api-reference/embeddings/create)

**Comment by logan-markewich** [comment]
I'm kind of surprised this works, since the new model isn't mentioned I'm the model dicts?

**Comment by hatianzhang** [comment]
@logan-markewich I am passing by `model_name`

**Comment by logan-markewich** [comment]
@hatianzhang ah I see. That code is way more confusing than it needs to be lol, cleanup for another pr though

**Comment by hatianzhang** [comment]
@logan-markewich now changed to model instead of model_name

**Comment by farzad528** [comment]
are the new embedding models available via Azure OpenAI with the dimensions parameter for text-embedding-3-large?

**Comment by logan-markewich** [comment]
@farzad528 as far as I know yes. They inherit from the normal openai embeddings class

**Pull request merged**
