### PR TITLE
Adds "Llamaindex-python" user agent to ai search requests

### PR DESCRIPTION
**Pull request by shthowse**
# Description
We want to be able to log telemetry to view AI Search indexes created and requests via LlamaIndex - Python integration. Added User-Agent=="Llamaindex-python" as a header

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [X ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [ X] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ X] I stared at the code and made sure it makes sense

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by logan-markewich** [comment]
We could have merged this 😅 Just had to figure out CICD. Feel free to reopen

**Comment by logan-markewich** [comment]
@farzad528 @shthowse any reason to close this? Seems like other Microsoft folks would appreciate this change

Feel free to re-open assuming this code works

**Comment by shakirthow** [comment]
I don't remember why we decided to close this, I'll review and re-open.

**Comment by shthowse** [comment]
@logan-markewich It looks like it should be okay to merge. Pls re-approve if needed

**Comment by farzad528** [comment]
can we merge?

**Comment by shthowse** [comment]
> can we merge?

Waiting for builds to pass, Will merge once done.

**Comment by shthowse** [comment]
@logan-markewich Thanks for taking a look at this :)
The updates unit tests are breaking, can you pls take a look when you get a chance.

**Comment by farzad528** [comment]
Hey @shakirthow @logan-markewich something is wrong with this PR in terms of authenticating the SearchIndexClient....

**Pull request merged**
