### PR TITLE
Update postgres.py

### PR DESCRIPTION
**Pull request by bogdanalexandrutreica**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by bogdanalexandrutreica** [comment]
#8910 bug
#8961

**Comment by tolexy** [comment]
This is still an issue when using 0.9.2. The same error is appearing. Using llama-index==0.9.2 in Google Colab. Code throws error when getting to the  PGVectorStore process. All worked fine a few days ago. Rolling back to previous versions of llama-index did not solve the issue either. I see the "fix" was merged, but it does not seem fixed. Any suggestions?

url = make_url(connection_string)
vector_store = PGVectorStore.from_params(
    database=db_name,
    host=url.host,
    password=url.password,
    port=url.port,
    user=url.username,
    table_name=table_name,
    embed_dim=1536,  
)


/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()
ValidationError: 1 validation error for PGVectorStore
use_jsonb
  field required (type=value_error.missing)

**Comment by bogdanalexandrutreica** [comment]
The fix is not in the v0.9.2 @tolexy
Lets hope that will be in v0.9.3 😄

**Comment by logan-markewich** [comment]
Correct, 0.9.2 was released before I merged this fix. Should be in 0.9.3 today

**Pull request merged**
