### PR TITLE
Add Llava MultiModal QA examples for Tesla 10k RAG

### PR DESCRIPTION
**Pull request by hatianzhang**
# Description

TODO:
Waiting for https://github.com/abetlen/llama-cpp-python supporting LlaVa model in python wrapper.
So LlamaIndex can leverage `LlamaCPP` class for serving LlaVa model directly.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
nice! 

some high-level comments:
- can you make the images also downlodable (right now they point to your local directory)
- the second example doesn't seem to change after you do retrieval
- ubernit: "*Multi-Modal" in the title

**Comment by jerryjliu** [comment]
@hatianzhang sorry just to clarify the second example doesn't seem to change. is this intentional?

**Comment by hatianzhang** [comment]
@jerryjliu the 1st example is `Tesla super charger` and 2nd examples is `Tesla Shanghai factory`.
The results from LlamaIndex for both examples are different.
Do I misunderstand ?

**Comment by hatianzhang** [comment]
@jerryjliu thanks for pointing it out. Now fixed!

**Review by jerryjliu — APPROVED** [review]
final nit is that the print statements now show formatted sources but not the actual string response. otherwise looks good!

**Comment by hatianzhang** [comment]
@jerryjliu thanks for feedback. Made the last change and now it should be good. 
Separate the query engine and response results. now it is more clear

**Pull request merged**
