### PR TITLE
Update Vectara Index

### PR DESCRIPTION
**Pull request by david-oplatka**
# Description

**Updating Vectara Managed Index**: This PR adds updated features to the Vectara Managed Index. Notably, we added our new User Defined Function reranker that allows users to specify their own function for how to rerank the search results. It also allows for all citation styles (markdown, html, and numeric), not just markdown. Lastly, we changed how we internally measure where people are using our index, adding a parameter for x_source_str (default value matches previous  functionality). Lastly, we expanded our README.md file to showcase a basic example of using our index and our demo notebook to showcase the new features (as well as our new python package, py-vectara-agentic).

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I added tests in [test_indices_managed_vectara.py](https://github.com/run-llama/llama_index/pull/15546/files#diff-1abce693e20de5e2f766a6e13a5039915e9ac60ccaa49c38456060064e439901) for the new udf reranker and citation styles. In order to run these tests, you need to run the test file from the top level directory in the repo (since we access a file in the docs folder). You will also need a Vectara account (Scale account to run citations tests) and a OPENAI api key in your environment (see test doc docstring for more info).

- [x] Added new unit/integration tests

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by nerdai — COMMENTED** [review]
Thanks @david-oplatka.

We just updated llama-index-core to v0.11 and updated all of integrations to be compatible with it, including this one.

Sorry, but could we add your updates on top of the latest version of this package?

**Comment by david-oplatka** [comment]
Hi @nerdai.

Yes, that should be totally fine. Thank you

**Comment by david-oplatka** [comment]
@nerdai I fixed all of the merge conflicts with main after the latest changes with v0.11. Is there anything else that you need me to complete before we can merge this component? It would be great if we can have this done by the end of the week.

Thanks again!

**Review by nerdai — APPROVED** [review]
LGTM!

**Pull request merged**
