### PR TITLE
make PydanticProgramExtractor importable from extractors

### PR DESCRIPTION
**Pull request by smowden**
# Description

The example code here https://gpt-index.readthedocs.io/en/latest/examples/metadata_extraction/PydanticExtractor.html
does not work because the module is not importable from extractors.

Fixes # (issue)
no issue

## Type of Change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by Disiok** [comment]
Thanks for the fix!

**Comment by smowden** [comment]
done

**Comment by Disiok** [comment]
hmm, now there's no change in the PR

**Comment by smowden** [comment]
checks are now finished, should be fine now

**Comment by smowden** [comment]
lol sorry my bad, should be good to go now

**Comment by Disiok** [comment]
Thanks!

**Pull request merged**
