### PR TITLE
Bugfix/code improvement for LanceDB integration

### PR DESCRIPTION
**Pull request by raghavdixit99**
# Description

Hi , 
I am from LanceDB team and there was an error in retrieving metadata while storing/accessing multimodal embeddings/metadata in Lance-LLama integration scripts. Have also added legacy fallback to handle any exceptions that may occur.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

unit tests were already added, I modified the example notebook to use LanceDB integration which also provides testing. Followed all make-build procedures and ensured all the tests passed.

- [x] Modified an existing example notebook 
- [x] I stared at the code and made sure it made sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by ravi03071991** [comment]
@raghavdixit99 as discussed can you please keep the original `image_to_image_retrieval.ipynb` notbook as it as and create a new notebook with a `LanceDB` use-case?

**Comment by hatianzhang** [comment]
agree with @ravi03071991 better to add a new notebook dedicated for `LanceDB`

**Comment by hatianzhang** [comment]
@raghavdixit99 pls just stash the changes to `image_to_image_retrieval.ipynb`
and your api key is disclosed. pls change it

**Comment by raghavdixit99** [comment]
Yes, noticed that have removed it , thanks.

**Comment by raghavdixit99** [comment]
@hatianzhang  kindly review it and let me know please, thanks

**Comment by raghavdixit99** [comment]
<p>added a hyper-link</p>

---

 <a href='https://app.reviewnb.com/run-llama/llama_index/pull/10144/discussion/#comment-1900935241'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by raghavdixit99** [comment]
<p>I have changed the markdown but the link will only work once the code is pushed as the path index is via the llama-index main branch</p>

---

 <a href='https://app.reviewnb.com/run-llama/llama_index/pull/10144/discussion/#comment-1900937474'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by raghavdixit99** [comment]
@hatianzhang have made the changes , pls review , thanks

**Review by hatianzhang — APPROVED** [review]

**Pull request merged**
