### PR TITLE
Hotfix: Forgot to increment `llama-index-llms-anthropic` to `v0.4.1`

### PR DESCRIPTION
**Pull request by brycecf**
# Description

Forgot to increment patch version when resolving conflict for PR #16896.  Consequently, that PR's changes haven't been released.

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Your pull-request will likely not be merged unless it is covered by some form of impactful unit testing.

- [ ] I added new unit tests to cover this change
- [x] I believe this change is already covered by existing unit tests

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by brycecf** [comment]
@logan-markewich Looks like the test files are being included in the coverage report: https://github.com/run-llama/llama_index/actions/runs/11800837492/job/32872700617?pr=16924#step:9:54

**Comment by logan-markewich** [comment]
@brycecf pushed a small change to exclude them, looks like it worked

**Review by logan-markewich — APPROVED** [review]

**Comment by brycecf** [comment]
@logan-markewich Could you please manually merge this to trigger the release?  The coverage fail is blocking the auto-merge.

**Comment by logan-markewich** [comment]
Oh apologies @brycecf , I thought I hit merge 😅

**Pull request merged**
