### PR TITLE
Add OpenVINO LLMs

### PR DESCRIPTION
**Pull request by OpenVINO-dev-contest**
# Description

Add OpenVINO LLMs

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by nerdai** [comment]
Thanks for the contribution @OpenVINO-dev-contest -- haven't taken a closer look yet, but just wondering would LogProbs be available for this LLM integration?

**Comment by Javtor** [comment]
General comment: Since `OpenVINOLLM` is very similar to `HuggingFaceLLM` (only `DEFAULT_HUGGINGFACE_MODEL`, the constructor, and `class_name` change) I would much prefer subclassing to avoid code-duplication, and changing the Pydantic fields default values and constructor as needed.

**Comment by OpenVINO-dev-contest** [comment]
> Pydantic

This is great idea, and thanks for your review, have updated it accordingly.

**Comment by OpenVINO-dev-contest** [comment]
> LogProbs

Hi since this implementation is a subclass of huggingface LLM, its functions will be aligned with HF.

**Comment by Javtor** [comment]
Thanks for the change! 
There seems to be a dependency conflict with the huggingface_hub version. This `pyproject.toml` requires `huggingface_hub<0.23.0 and >=0.22.2`, but the one from `llama-index-llms-huggingface` requires it to be `<0.21.0 and >=0.20.3`

**Comment by OpenVINO-dev-contest** [comment]
> dependency

removed the conflict dependency to align with HF.

**Review by Javtor — APPROVED** [review]
Lgtm

**Pull request merged**
