### PR TITLE
feat: Spider Web Loader

### PR DESCRIPTION
**Pull request by WilliamEspegren**
# Description

Added SpiderWebLoader, the fastest and cheapest crawler that returns LLM-ready data.

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end) (added in existing notebook)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by WilliamEspegren** [comment]
@logan-markewich now lint and the unit test should pass

**Comment by WilliamEspegren** [comment]
@logan-markewich anything blocking this?

**Comment by nerdai** [comment]
merging this now @WilliamEspegren and @logan-markewich!

**Comment by WilliamEspegren** [comment]
@nerdai the version must be bumped: 

Change this [line](https://github.com/run-llama/llama_index/blob/c9225877bc45a8242a27e7872a3f8269ef818d2a/llama-index-integrations/readers/llama-index-readers-web/pyproject.toml#L45) to 01.1.13

**Comment by WilliamEspegren** [comment]
> Ah shucks. My bad. Can you submit another PR to bump version?

Here you go: https://github.com/run-llama/llama_index/pull/13301

**Pull request merged**
