### PR TITLE
Box reader

### PR DESCRIPTION
**Pull request by barduinor**
# Description

This open-source integration brings the capabilities of Box.com to the LLama-Index, empowering developers building Retrieval Augmented Generation (RAG) and other LLM applications.

We provide multiple readers, including:

- [Box Reader](llama_index/readers/box/BoxReader/README.md) - Implementation of the SimpleReader interface to read files from Box.
- [Box Text Extraction](llama_index/readers/box/BoxReaderTextExtraction/README.md) - Uses Box text representation to extract text from document.
- [Box AI Prompt](llama_index/readers/box/BoxReaderAIPrompt/README.md) - Uses Box AI to extract context from documents
- [Box AI Extraction](llama_index/readers/box/BoxReaderAIExtraction/README.md) - Uses Box AI to extract structured data from documents

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No (new reader)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks (no notebooks).
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
@barduinor Thank you for adding the mixins! That was the one thing from the other PR I was going to port over 😅

**Comment by barduinor** [comment]
Hi @logan-markewich , yes I was working on those this morning, and still completing them for the other Box reader classes.

**Comment by logan-markewich** [comment]
@barduinor Yea as discussed a few minutes ago, I think the `FileSystemReaderMixin` only makes sense on the basic box reader.

The idea there is to provide a method to get just the raw file content (I.e. the bytes) instead of a parsed document object

**Comment by logan-markewich** [comment]
I took a quick look, I think it might look something like this (probably not quite correct, but close)

```python
        def read_file_content(self, input_file: Path, **kwargs) -> bytes:
        """
        Read the bytes content of a file. 

        Args:
            input_file (Path): Path to the file. Assumes the file is in the format `file_id`.

        Returns:
            bytes: File content.
        """
        # Connect to Box
        box_check_connection(self._box_client)

        file_id = input_file.stem
        file = self._box_client.file(file_id).get()
        return file.content()

```

**Comment by barduinor** [comment]
@logan-markewich 

Latest updates:
- `FileSystemReaderMixin`
- Refactor to eliminate duplicate code
- Revamp README.md (all of them)

Let us know if you have more feedback

**Review by logan-markewich — APPROVED** [review]
Amazing, looks great!

**Comment by chetanchoudhary** [comment]
> Amazing, looks great!

Hey @logan-markewich , @barduinor : Publishing of this package has failed, due to which we are not able to poetry add or pip install it, I have attached the screenshot of failure.

Screenshot from 2024-07-15 18-02-53

**Pull request merged**
