### PR TITLE
Support all filter operators for Milvus vector store

### PR DESCRIPTION
**Pull request by RussellLuo**
This PR is a followup of #13591. It's mostly motivated by [Logan's comment](https://github.com/run-llama/llama_index/pull/13591#discussion_r1607199654) and #13742 (somehow related although not entirely certain).

### CODE REVIEW

**Comment by RussellLuo** [comment]
image

Why a list of integers is not supported? I noticed that only `List[StrictStr]` is allowed in `MetadataFilter`:

https://github.com/run-llama/llama_index/blob/a36984e93ec23878a61cbe379000d10f0cb8fd63/llama-index-core/llama_index/core/vector_stores/types.py#L87-L98

**Comment by logan-markewich** [comment]
Hmm, not sure @RussellLuo maybe an oversight? It could be updated

**Comment by RussellLuo** [comment]
I found that the support for `List[StrictInt]` and `List[StrictFloat]` was removed by #13365. I think the support for them should be restored.

@logan-markewich Additionally, I think [the names of the newly-added "any" and "all" are too generic](https://github.com/run-llama/llama_index/pull/13365#discussion_r1615399487) , thoughts?

**Comment by RussellLuo** [comment]
Hi @logan-markewich, you guys are too busy (appreciated for the hard work 😄). Is there any chance for this PR to be merged?

**Comment by logan-markewich** [comment]
Sorry @RussellLuo this slipped through the cracks, lemme take a look again

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
