### PR TITLE
Fix bug where PDFReader ignores extra_info

### LINKED ISSUE #13290: [Bug]: PDFReader doesn't add `extra_info` into metadatas if  `return_full_document` is `True`
### Bug Description

Using a PDFReader with `return_full_document=True` doesn't add `extra_info` into metadatas.

Default PDFReader (`return_full_document=False`) and others default readers seem to all add these extra infos.

Seems like these two lines are missing in `PDFReader.load_data`:
```python
if extra_info is not None:
    metadata.update(extra_info)
```

### Version

0.10.28

### Steps to Reproduce

```python
input_files = ['file/path/1.pdf', 'file/path/2.pdf']
metadatas = {
    'file/path/1.pdf': {'info': 'test1'},
    'file/path/2.pdf': {'info': 'test2'}
}
file_metadata = lambda x: metadatas[x]

### Split per page (= multiple Documents created), metadata added
documents1 = SimpleDirectoryReader(input_files=input_files , file_metadata=file_metadata).load_data()

### Keep whole files (= 2 Documents created), metadata NOT added
file_extractor = {".pdf": PDFReader(return_full_document=True)}
documents2 = SimpleDirectoryReader(input_files=input_files , file_metadata=file_metadata, file_extractor=file_extractor).load_data()
```

### Relevant Logs/Tracbacks

_No response_

### PR DESCRIPTION
**Pull request by joelrorseth**
# Description

Fixing a bug where `PDFReader` doesn't add `extra_info` into document metadata when `return_full_document == True`. Also, I fixed an apparent bug in PDFReader where, when extracting the text from each PDF page and merging into a single document (i.e., when `return_full_document == True`), the page texts are naively concatenated into a single string with no separator. This will lead to situations where the last word of page 1 is literally concatenated with the first word of page 2, etc. I added a newline separator instead (open to suggestions, a simple space character might suffice). Also, added new tests to test PDFReader behaviors related to loading data and metadata.

Fixes #13290

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by nerdai — APPROVED** [review]
nice @joelrorseth! ~I think we that might need to run `pants tailor ::` tho as the checks are not passing.~

**Comment by joelrorseth** [comment]
Thanks @nerdai for the review! Logan and I agree to bring in `fpdf2` as a dev dependency for my tests, I must not have declared this properly. I put it under `[tool.poetry.group.dev.dependencies]` in the local `pyproject.toml`, do you know if I need to declare it elsewhere?

**Comment by nerdai** [comment]
> Thanks @nerdai for the review! Logan and I agreed to bring in `fpdf2` as a dev dependency for my tests, I must not have declared this properly. I put it under `[tool.poetry.group.dev.dependencies]` in the local `pyproject.toml`, do you know if I need to declare it elsewhere?

It might just be a pants related issue. Trying to take a look into this now :)

**Comment by nerdai** [comment]
lol @joelrorseth i'm playing around with github cli and i may have closed your PR by acccident 😂

**Pull request merged**
