### PR TITLE
Added feature to stream_chat allowing previous chunks to be inserted into the current context window

### PR DESCRIPTION
**Pull request by rohans30**
# Description

When using various RAG pipelines. oftentimes questions such as "Can you elaborate?" or "Can you explain further?" are unable to be answered. This is due to the fact that the embedding model will search for chunks in the documents that match this exact query instead of reusing the chunks from the previous questions, and therefore the LLM will claim that this question is out of context.

To fix this, I maintained a history of the previous chunks fetched from previous queries and used the SimilarityProcessor to ensure all chunks with scores below 0.05 are not added to the context. This ensures that questions such as "Can you elaborate" have empty context windows since all the chunks found have scores of around 0.001. Then, I passed in a list of previous chunks into the stream_chat function as an optional parameter, and if the context window is empty, I insert hose previous chunks into the current context window by editing the context string. 

I am using PrivateGPT, so the code that handles the SimilarityProcessor and the history of previous chunks is handled in PrivateGPT's codebase.

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [X] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [X] No

## Type of Change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I tested this in my local PrivateGPT setup by asking various questions like "Can you elaborate?" and "Can you repeat that?" and ensured that the LLM was receiving the right chunks.

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [X] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
We should add this to all methods, not just stream_chat

**Comment by rohans30** [comment]
> We should add this to all methods, not just stream_chat

Added to all functions

**Review by logan-markewich — APPROVED** [review]

**Comment by rohans30** [comment]
Is there something special I need to do to have the unit tests pass?

**Comment by rohans30** [comment]
@logan-markewich Can this get merged?

**Comment by rohans30** [comment]
@logan-markewich Can this get merged?

**Comment by logan-markewich** [comment]
@rohans30 I just realized that `prev_chunks` is missing a type. How its used, it seems like its a list of lists for some reason? That doesn't really make any sense 😓 

In a future PR (#14883) this will be refactored to be `Optional[List[NodeWithScore]]` which is more user friendly I think, but also a breaking change for you, so just a heads up

**Comment by rohans30** [comment]
@logan-markewich I chose to use a list of lists because I save the list of previous nodes in a sliding window everytime a question is asked, and then append that list to a larger list of lists. Making it just one list is fine too, all the sub lists can just be merged together.

**Pull request merged**
