### PR TITLE
chore: + the linter `mypy` as a pre-commit hook

### PR DESCRIPTION
**Pull request by tslmy**
# Description

No more surprises like [this](https://github.com/run-llama/llama_index/pull/9789#issuecomment-1873522945).

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by tslmy** [comment]
I see a bunch of existing problems:

```
llama_index/embeddings/pooling.py:18: error: Never has no attribute "cls_pooling"  [attr-defined]
llama_index/embeddings/pooling.py:28: error: Overloaded function signature 2 will never be matched: signature 1's parameter type(s) are the same or broader  [misc]
llama_index/graph_stores/registry.py:23: error: Only concrete class can be given where "Tuple[GraphStoreType, Type[GraphStore]]" is expected  [type-abstract]
llama_index/llms/loading.py:29: error: Only concrete class can be given where "Tuple[str, Type[LLM]]" is expected  [type-abstract]
llama_index/objects/base_node_mapping.py:93: error: Incompatible types in assignment (expression has type "Type[BaseObjectNodeMapping[Any]]", variable has type "Type[BaseObjectNodeMapping[OT]]")  [assignment]
llama_index/objects/base_node_mapping.py:93: note: Error code "assignment" not covered by "type: ignore" comment
llama_index/objects/base_node_mapping.py:93: error: Can only assign concrete classes to a variable of type "Type[BaseObjectNodeMapping[OT]]"  [type-abstract]
llama_index/objects/base_node_mapping.py:93: note: Error code changed to type-abstract; "type: ignore" comment may be out of date
llama_index/indices/common_tree/base.py:225: error: Incompatible types in assignment (expression has type "Tuple[str]", variable has type "List[Tuple[str, str]]")  [assignment]
llama_index/response_synthesizers/tree_summarize.py:118: error: "str" has no attribute "json"  [attr-defined]
llama_index/vector_stores/redis.py:38: error: Library stubs not installed for "redis.commands.search.field"  [import-untyped]
llama_index/vector_stores/redis.py:38: note: Hint: "python3 -m pip install types-redis"
llama_index/vector_stores/redis.py:38: note: (or run "mypy --install-types" to install all missing stub packages)
llama_index/vector_stores/redis.py:38: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
llama_index/vector_stores/redis.py:344: error: Library stubs not installed for "redis.commands.search.indexDefinition"  [import-untyped]
llama_index/vector_stores/cassandra.py:292: error: Incompatible types in assignment (expression has type "List[Never]", variable has type "Tuple[Any, ...]")  [assignment]
llama_index/vector_stores/cassandra.py:293: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "Tuple[Any, ...]")  [assignment]
llama_index/vector_stores/cassandra.py:294: error: Incompatible types in assignment (expression has type "List[Any]", variable has type "Tuple[Any, ...]")  [assignment]
llama_index/vector_stores/cassandra.py:297: error: Argument 2 to "get_top_k_mmr_embeddings" has incompatible type "Tuple[Any, ...]"; expected "List[List[float]]"  [arg-type]
llama_index/vector_stores/cassandra.py:299: error: Argument "embedding_ids" to "get_top_k_mmr_embeddings" has incompatible type "Tuple[Any, ...]"; expected "Optional[List[Any]]"  [arg-type]
tests/vector_stores/test_elasticsearch.py:59: error: Missing return statement  [return]
llama_index/llama_dataset/base.py:65: error: Can only assign concrete classes to a variable of type "Type[BaseLlamaExamplePrediction]"  [type-abstract]
llama_index/llama_dataset/base.py:65: note: Error code changed to type-abstract; "type: ignore" comment may be out of date
llama_index/llama_dataset/base.py:115: error: Can only assign concrete classes to a variable of type "Type[BaseLlamaDataExample]"  [type-abstract]
llama_index/llama_dataset/base.py:115: note: Error code changed to type-abstract; "type: ignore" comment may be out of date
```

Might need some time to fix them before adding `mypy`.

**Comment by logan-markewich** [comment]
I think this is because the hook you added updates the mypy version?

**Comment by logan-markewich** [comment]
Nice, that looks much better to fix 😅

**Comment by tslmy** [comment]
@logan-markewich , yeah. But I decided to bump it to a newer version that would not yield these complaints:

```
llama_index/llms/perplexity.py:244: error: Self? has no attribute "post"  [attr-defined]
llama_index/llms/perplexity.py:321: error: Self? has no attribute "post"  [attr-defined]
llama_index/llms/llama_cpp.py:186: error: Self? has no attribute "headers"  [attr-defined]
llama_index/llms/llama_cpp.py:190: error: Self? has no attribute "headers"  [attr-defined]
llama_index/llms/llama_cpp.py:196: error: Self? has no attribute "iter_content"  [attr-defined]
```

**Pull request merged**
