### PR TITLE
Make unit testing (usually) mandatory

### PR DESCRIPTION
**Pull request by logan-markewich**
Fixes https://github.com/run-llama/llama_index/issues/16370

### CODE REVIEW

**Comment by brycecf** [comment]
Could a minimum coverage requirement also be added?

Not sure a good way to do without blocking all new PRs in the immediate though...

**Comment by logan-markewich** [comment]
Yea @brycecf minimum coverage is pretty hard, especially with a monorepo

**Comment by masci** [comment]
@brycecf it would be a bit invasive doing it in the pre-commit, but I would support having a CI check in the PR, services like codecov can even leave comments to explain how the current coverage went down

**Comment by logan-markewich** [comment]
@masci would codecov only check coverage for the latest changes in a given PR?

**Review by masci — APPROVED** [review]
💯

**Comment by masci** [comment]
@logan-markewich yes, the coverage would be measured against the PR branch and compared with main, showing how it would change after merging

**Pull request merged**
