### PR TITLE
Add Uptrain Callback Handler

### PR DESCRIPTION
**Pull request by Dominastorm**
# Description

Add the UpTrainCallbackHandler to perform evaluations on query, context and response in the llamindex pipeline. 

Fixes # (issue)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by Dominastorm** [comment]
Hey @hatianzhang,

Just wanted to give a friendly ping on this PR. It's been a little over a week since I submitted it, and I understand everyone's busy. I just wanted to make sure it didn't slip through the cracks.

If there's anything I can do to help move this forward or provide additional context, please let me know!

Thanks!

**Comment by hatianzhang** [comment]
@Dominastorm thanks for your contribution.
We are now in code freeze so I am not going to merge your pr atm. Once our 0.10.0 going out. I will merge this one asap

**Comment by logan-markewich** [comment]
@Dominastorm  apologies, with v0.10.0 the project structure has changed slightly

I can take a stab at porting this PR in a bit, if you don't get to it first :)

**Comment by Dominastorm** [comment]
@logan-markewich thanks for the offer! I'll port it, no worries :)

**Comment by Dominastorm** [comment]
@logan-markewich, I have made the changes for porting. I tested it locally and it is working in the python notebook. However, I am unable to understand the test that is failing. If you could let me know what exactly it means, I can get started on fixing it. Thanks!

**Comment by logan-markewich** [comment]
@Dominastorm It seems I cant push to your PR, but I can tell you how to make CICD pass :) 

[Install pants](https://www.pantsbuild.org/2.19/docs/getting-started/installing-pants)
Run `pants tailor ::`
add/commit/push and BUILD files it created

**Comment by Dominastorm** [comment]
Thanks @logan-markewich! The PR is ready for review now :)

**Review by hatianzhang — COMMENTED** [review]
LGTM!

**Review by hatianzhang — APPROVED** [review]

**Pull request merged**
