### PR TITLE
feat: extract title for nodes based on refId

### PR DESCRIPTION
**Pull request by EmanuelCampos**
# Description

Before titles was extracted as the same for all ingested documents, now titles are generated based on ref_doc_id and combined to one

big s/o to @yisding for find the incorrect behavior

# Output example

```json
[
   {
      "title":"Exploring the Diverse Entities and Themes in Paul Graham's Essays",
      "id":"12739816-68ea-451a-aa84-fbb9ce158189",
      "ref_id":"d96bb0f0-1f81-4f0a-9b20-90494a1f07b7"
   },
   {
      "title":"Exploring the Diverse Entities and Themes in Paul Graham's Essays",
      "id":"3fa56b2c-4df9-4679-8052-e4991a662dbc",
      "ref_id":"d96bb0f0-1f81-4f0a-9b20-90494a1f07b7"
   },
   {
      "title":"\"The Enigmatic Blue Dog: Unveiling Uniqueness, Mystery, and Intrigue - The Joyful Canine: A Tale of Happiness and Contentment\"",
      "id":"8f0f7382-f017-4b93-8295-5f27177c5daa",
      "ref_id":"ca8c0567-3524-4b10-ace6-e85f0bee8e53"
   },
   {
      "title":"\"The Enigmatic Blue Dog: Unveiling Uniqueness, Mystery, and Intrigue - The Joyful Canine: A Tale of Happiness and Contentment\"",
      "id":"2ccf7593-1de1-4845-b77f-ec5536806828",
      "ref_id":"ca8c0567-3524-4b10-ace6-e85f0bee8e53"
   },
   {
      "title":"\"The Avian World: A Comprehensive Exploration of the Diversity, Wonders, and Fascinating Aspects of Birds\"",
      "id":"12015ec7-b532-4cc7-8513-1d06a2aa9c98",
      "ref_id":"88497d58-d62d-4976-857c-a4523908afec"
   },
   {
      "title":"\"The Avian World: A Comprehensive Exploration of the Diversity, Wonders, and Fascinating Aspects of Birds\"",
      "id":"9539e607-24c6-4590-891b-e9f64b2a948d",
      "ref_id":"88497d58-d62d-4976-857c-a4523908afec"
   }
]
```

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]
Makes a lot of sense, exactly what I would have done :)

**Comment by EmanuelCampos** [comment]
> Makes a lot of sense, exactly what I would have done :)

só I'm doing very well haha, what a honor

**Comment by hackgoofer** [comment]
Hey, sorry to report this. But I found that this PR introduced a bug, I tested it and it was working before, but with this PR it is no longer working.
Screenshot 2024-01-23 at 4 04 50 PM

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[9], [line 5](vscode-notebook-cell:?execution_count=9&line=5)
      [1](vscode-notebook-cell:?execution_count=9&line=1) from llama_index.ingestion import IngestionPipeline
      [3](vscode-notebook-cell:?execution_count=9&line=3) pipeline = IngestionPipeline(transformations=transformations)
----> [5](vscode-notebook-cell:?execution_count=9&line=5) uber_nodes = pipeline.run(documents=uber_docs)

File [~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:466](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:466), in IngestionPipeline.run(self, show_progress, documents, nodes, cache_collection, in_place, store_doc_text, num_workers, **kwargs)
    [464](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:464)         nodes = reduce(lambda x, y: x + y, nodes_parallel)
    [465](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:465) else:
--> [466](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:466)     nodes = run_transformations(
    [467](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:467)         nodes_to_run,
    [468](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:468)         self.transformations,
    [469](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:469)         show_progress=show_progress,
    [470](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:470)         cache=self.cache if not self.disable_cache else None,
    [471](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:471)         cache_collection=cache_collection,
    [472](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:472)         in_place=in_place,
    [473](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:473)         **kwargs,
    [474](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:474)     )
    [476](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:476) if self.vector_store is not None:
    [477](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:477)     self.vector_store.add([n for n in nodes if n.embedding is not None])

File [~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:80](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:80), in run_transformations(nodes, transformations, in_place, cache, cache_collection, **kwargs)
     [78](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:78)         nodes = cached_nodes
     [79](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:79)     else:
---> [80](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:80)         nodes = transform(nodes, **kwargs)
     [81](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:81)         cache.put(hash, nodes, collection=cache_collection)
     [82](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/ingestion/pipeline.py:82) else:

File [~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:155](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:155), in BaseExtractor.__call__(self, nodes, **kwargs)
    [147](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:147) def __call__(self, nodes: List[BaseNode], **kwargs: Any) -> List[BaseNode]:
    [148](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:148)     """Post process nodes parsed from documents.
    [149](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:149) 
    [150](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:150)     Allows extractors to be chained.
   (...)
    [153](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:153)         nodes (List[BaseNode]): nodes to post-process
    [154](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:154)     """
--> [155](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:155)     return self.process_nodes(nodes, **kwargs)

File [~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:138](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:138), in BaseExtractor.process_nodes(self, nodes, excluded_embed_metadata_keys, excluded_llm_metadata_keys, **kwargs)
    [131](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:131) def process_nodes(
    [132](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:132)     self,
    [133](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:133)     nodes: List[BaseNode],
   (...)
    [136](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:136)     **kwargs: Any,
    [137](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:137) ) -> List[BaseNode]:
--> [138](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:138)     return asyncio.run(
    [139](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:139)         self.aprocess_nodes(
    [140](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:140)             nodes,
    [141](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:141)             excluded_embed_metadata_keys=excluded_embed_metadata_keys,
    [142](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:142)             excluded_llm_metadata_keys=excluded_llm_metadata_keys,
    [143](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:143)             **kwargs,
    [144](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:144)         )
    [145](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:145)     )

File [~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:31](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:31), in _patch_asyncio.<locals>.run(main, debug)
     [29](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:29) task = asyncio.ensure_future(main)
     [30](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:30) try:
---> [31](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:31)     return loop.run_until_complete(task)
     [32](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:32) finally:
     [33](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:33)     if not task.done():

File [~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:99](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:99), in _patch_loop.<locals>.run_until_complete(self, future)
     [96](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:96) if not f.done():
     [97](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:97)     raise RuntimeError(
     [98](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:98)         'Event loop stopped before Future completed.')
---> [99](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/site-packages/nest_asyncio.py:99) return f.result()

File [~/miniconda3/envs/llama/lib/python3.11/asyncio/futures.py:203](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/futures.py:203), in Future.result(self)
    [201](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/futures.py:201) self.__log_traceback = False
    [202](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/futures.py:202) if self._exception is not None:
--> [203](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/futures.py:203)     raise self._exception.with_traceback(self._exception_tb)
    [204](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/futures.py:204) return self._result

File [~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:277](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:277), in Task.__step(***failed resolving arguments***)
    [273](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:273) try:
    [274](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:274)     if exc is None:
    [275](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:275)         # We use the `send` method directly, because coroutines
    [276](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:276)         # don't have `__iter__` and `__next__` methods.
--> [277](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:277)         result = coro.send(None)
    [278](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:278)     else:
    [279](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/miniconda3/envs/llama/lib/python3.11/asyncio/tasks.py:279)         result = coro.throw(exc)

File [~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:116](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:116), in BaseExtractor.aprocess_nodes(self, nodes, excluded_embed_metadata_keys, excluded_llm_metadata_keys, **kwargs)
    [113](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:113) else:
    [114](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:114)     new_nodes = [deepcopy(node) for node in nodes]
--> [116](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:116) cur_metadata_list = await self.aextract(new_nodes)
    [117](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:117) for idx, node in enumerate(new_nodes):
    [118](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/interface.py:118)     node.metadata.update(cur_metadata_list[idx])

File [~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:109](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:109), in TitleExtractor.aextract(self, nodes)
    [107](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:107) nodes_by_doc_id = self.separate_nodes_by_ref_id(nodes_to_extract_title)
    [108](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:108) titles_by_doc_id = await self.extract_titles(nodes_by_doc_id)
--> [109](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:109) return [{"document_title": titles_by_doc_id[node.ref_doc_id]} for node in nodes]

File [~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:109](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:109), in <listcomp>(.0)
    [107](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:107) nodes_by_doc_id = self.separate_nodes_by_ref_id(nodes_to_extract_title)
    [108](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:108) titles_by_doc_id = await self.extract_titles(nodes_by_doc_id)
--> [109](https://file+.vscode-resource.vscode-cdn.net/Users/sasha/github/LlamaIndex/Experiments/~/github/LlamaIndex/llama_index/llama_index/extractors/metadata_extractors.py:109) return [{"document_title": titles_by_doc_id[node.ref_doc_id]} for node in nodes]

KeyError: '3b71eb37-4447-4630-9b55-25f382047ae4'
```

**Comment by EmanuelCampos** [comment]
@hackgoofer can you send a reproducible example? some code snippets, your screenshot isn't complete

**Pull request merged**
