### PR TITLE
Fix DuckDBVectorStore

### PR DESCRIPTION
**Pull request by wencan**
# Description

@krish-adi 
I encountered two issues while using DuckDBVectorStore:

DuckDBVectorStore.from_local does not support specifying embed_dim, causing my code to malfunction.

DuckDBVectorStore only loads the main fields of the Node.

This PR addresses the aforementioned issues.

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by logan-markewich** [comment]
:sigh: -- this package is published by someone else for some reason. I'm tempted to change the package name just to have control over it again

**Comment by wencan** [comment]
@krish-adi 
Can you transfer the ownership of the package llama-index-vector-stores-duckdb to the team llamaindex?
The package llama-index-vector-stores-duckdb on PyPI is now three minor versions behind.

**Comment by krish-adi** [comment]
@wencan who do i transfer the ownership too?

**Comment by logan-markewich** [comment]
@krish-adi can you transfer to jerry? https://pypi.org/user/jerryjliu/

**Comment by krish-adi** [comment]
@logan-markewich I had sent the invite to https://pypi.org/user/jerryjliu/ earlier and it wasn't accepted. 
Screenshot 2024-06-21 at 17 28 26

i've sent another invite now. could you confirm when it's accepted?

**Comment by krish-adi** [comment]
@logan-markewich it looks like the invite was accepted.

**Comment by krish-adi** [comment]
@logan-markewich was the permissions good for updating the package?

**Comment by logan-markewich** [comment]
@krish-adi yes it worked, thank you!

**Pull request merged**
