### PR TITLE
Remove deprecated code in vector store

### PR DESCRIPTION
**Pull request by Disiok**
# Description

Clean up

### CODE REVIEW

**Comment by logan-markewich** [comment]
Do you think there's any way for us to provide a method for upgrading existing vector stores? Fetch all nodes and re-insert them?

Low key a little worried by how many people this will impact 🤔

**Comment by Disiok** [comment]
my claim is that the impact will be minimal: any code that's using the legacy representation would be using a client **many** minor versions behind. So either version is pinned or there would've been many breaking changes along the way which result in updating the code and re-indexing.

**Comment by logan-markewich** [comment]
Actually, they could be impacted if they have any nodes indexed using old clients. They could be on the latest version today but still hit this issue.

I can think of a few people using LlamaIndex in production who might get hit by this 🤔 And re-indexing might not be an option when they are operating with user-uploaded data

**Comment by Disiok** [comment]
Good point, maybe the right approach is to start raising deprecation warnings and provide migration tool as first step. 

Let's not do this for 0.9 then

**Pull request closed without merging**
