### PR TITLE
Revert "bump google-generativeai to 0.4 (#12085)"

### PR DESCRIPTION
**Pull request by hatianzhang**
This reverts commit 434982cb9051c8a8be5dbc5e00208c78b8d7f7b7.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by nicoloboschi** [comment]
@logan-markewich @hatianzhang could you explain why you reverted the PR? 
could you add the error/problem to this PR's description?

**Comment by logan-markewich** [comment]
@nicoloboschi it was causing some error (possibly?) in gemini responses. I think it could maybe be bumped back, extra assuming it doesn't break anything

https://github.com/run-llama/llama_index/issues/12100

**Comment by nicoloboschi** [comment]
Thanks for pointing out the issue, I will take a look

**Comment by nicoloboschi** [comment]
@logan-markewich I looked at the problem. @ujjwalk906 was having issue because he wasn't using a llamaindex version containing this fix: https://github.com/run-llama/llama_index/pull/11511. The KeyError "model" is pretty clear now.
 
In fact, after he upgraded to 0.10.21 (with that fix in) things started to work correctly.

Also he fixed his problem WITHOUT reverting the google gen upgrade (also your revert is not even released today).

In conclusion, I will re-create the PR with the upgrade (I did more manual tests and everything looks good on my side)

**Pull request merged**
