### PR TITLE
Add input_type to VoyageEmbedding

### PR DESCRIPTION
**Pull request by thomas0809**
# Description

Add input_type to VoyageEmbedding

## Type of Change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by hatianzhang** [comment]
@thomas0809 did not find this new input_type from https://docs.voyageai.com/embeddings/
Do I miss anything

**Comment by thomas0809** [comment]
We will be updating the docs shortly. You can check our repo https://github.com/voyage-ai/voyageai-python

**Comment by hatianzhang** [comment]
@thomas0809 awesome. so basically the query and document encoder are different from voyage?

**Review by hatianzhang — APPROVED** [review]
LGTM
@thomas0809 maybe worth try to run thru `/llama_index/docs/examples/embeddings/voyageai.ipynb`

**Comment by thomas0809** [comment]
> LGTM @thomas0809 maybe worth try to run thru `/llama_index/docs/examples/embeddings/voyageai.ipynb`

This has been validated.

**Pull request merged**
