### PR TITLE
fix `SimpleVectorStore.from_persist_dir()` behaviour

### PR DESCRIPTION
**Pull request by polarbear567**
# Description

1. Due to the default addition of namespace to the file name in the persist operation, this modification has set the default namespace to default and always uses namespace as a prefix for querying.
2. Add some test cases.

Fixes https://github.com/run-llama/llama_index/issues/15451

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

Just run the test cases. If you use the code before modification, you can reproduce the problem through my newly added test case.

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

Hey, this is my first pr in this repo, please suggest anything that you think can be improved, thank you.

### CODE REVIEW

**Review by masci — CHANGES_REQUESTED** [review]
Hi @polarbear567 and thanks for your contribution!

Can you add a unit test covering this code change? Aside from this specific PR, it usually helps a lot the reviewer if you add a brief explanation of the change in the PR description, just follow the template for the next PRs 😉

**Comment by polarbear567** [comment]
Sure, will update this PR.

**Comment by polarbear567** [comment]
Hi @masci 
I add a pr description and test cases, pls help to review, thx!

**Comment by polarbear567** [comment]
Hi @masci 
I see some issues about other files, do I need to do anything else?

**Comment by masci** [comment]
Sorry @polarbear567 this took so long, it was caught in the middle of our migration to Pydantic v2, merging now!

**Review by masci — APPROVED** [review]

**Pull request merged**
