### PR TITLE
replicate_multi_model changes to reduce number of cold boots

### PR DESCRIPTION
**Pull request by donbr**
# Description

Although the code in the "Generate Image Reasoning..." section works it takes a long time and incurs a huge cold boot penalty each time it switches models.  To avoid this I recommend a simple resequencing in the "for" loops to group operations for the same model together.  The change improves performance significantly - and was a much more respectful use of Replicate resources.

Existing order
```python
for prompt_idx, prompt in enumerate(prompts):
    for image_idx, image_doc in enumerate(image_documents):
        for llm_idx, llm_model in enumerate(REPLICATE_MULTI_MODAL_LLM_MODELS):
```

Current change - recommended order for SIGNIFICANT performance boost
```python
for llm_idx, llm_model in enumerate(REPLICATE_MULTI_MODAL_LLM_MODELS):
    for image_idx, image_doc in enumerate(image_documents):
        for prompt_idx, prompt in enumerate(prompts):
```

### Documentation Link

https://github.com/run-llama/llama_index/blob/main/docs/examples/multi_modal/replicate_multi_modal.ipynb

Fixes # [11666](https://github.com/run-llama/llama_index/issues/11666)

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ x ] Added new unit/integration tests
- [ x ] Added new notebook (that tests end-to-end)
- [ x ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] I have added Google Colab support for the newly added notebooks.
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by donbr** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/run-llama/llama_index/pull/11673/discussion/#comment-1979965656'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by logan-markewich — COMMENTED** [review]
Can we keep the notebook cell outputs though? Especially for the actual LLM calls

**Comment by logan-markewich** [comment]
@donbr just a small ping, if possible, keeping the actual LLM outputs in the notebook is very helpful for users

**Comment by logan-markewich** [comment]
Going to close this one out for now, its quite outdated at this point

If its still an issue, please raise an updated PR

Sorry for letting this one sit for so long!

**Pull request closed without merging**
