### PR TITLE
v0.10.20

### PR DESCRIPTION
**Pull request by logan-markewich**

### CODE REVIEW

**Review by anoopshrma — APPROVED** [review]

**Review by nerdai — APPROVED** [review]
I should probably cut a release with the new setup soon lol 😂 -- thanks for doing this!

**Comment by anoopshrma** [comment]
New setup 👀 curious to know about it!! 
As in new assembled machine or more powerful Mac 😅

**Comment by logan-markewich** [comment]
@anoopshrma oh, I think Andrei meant with our new release process 💪🏻

**Comment by anoopshrma** [comment]
Lol 😆

**Comment by logan-markewich** [comment]
@anoopshrma basically,
- bump and publish core
- go through all PRs and
    - bump and versions in pyproject.toml files that got missed
    - Fill out changelog (see the new format here)
    - update the root pyproject.toml and run poetry lock
    - make this PR
    - merge this PR
    - create a new version tag to trigger a top-level release on GitHub and docs

**Pull request merged**
