### PR TITLE
refactor: improve model loading, weighted pooling fix t5 model loading

### PR DESCRIPTION
**Pull request by bwanglzu**
# Description

i made several changes to the HF embedding class to:

1. allow pass `model_args` and `tokenizer_args` to the auto classes, this could allow user to specify some important parameters, such as `revision` or `trust_remote_code`.
2. fix t5 model loading, it uses a different architecture than other models.
3. added `weighted mean pooling`, allows use LLM as an embedding model, proposed in SGPT paper.
4. Not sure if i should do it or not, i renamed `model_name` to `model_name_or_path` to keep consistent with HF. I can revert this change to avoid breaking change.
5. Change the default pooling to `mean` since it always brings better embedding quality compared to cls. Please refenrece to sbert paper or sentence-t5 paper.

~Something quite confuse me is in the current implementation, the class allows not only `model_name` but also a `model` to be passed into the constructor, my personal suggestion is keeping `model_name` and `cache_dir` is sufficiently enough.~

fyi @logan-markewich 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by bwanglzu** [comment]
i made several changes to the HF embedding class to:

1. allow pass `model_args` and `tokenizer_args` to the auto classes.
2. fix t5 model loading, it uses a different architecture than other models.
3. added `weighted mean pooling`, allows use LLM as an embedding model, proposed in SGPT paper.
4. Not sure if i should do it or not, i renamed `model_name` to `model_name_or_path` to keep consistent with HF. I can revert this change to avoid breaking change.

Something quite confuse me is in the current implementation, the class allows not only `model_name` but also a `model` to be passed into the constructor, my personal suggestion is keeping `model_name` and `cache_dir` is sufficiently enough.

fyi @logan-markewich

**Comment by logan-markewich** [comment]
Thanks @bwanglzu !

The reason the both model or model_name are inputs is because there are endless ways to load a model. So, we all you to pass the model/tokenizer in directly so that the user can skip the default loading code

**Comment by bwanglzu** [comment]
i see @logan-markewich i'll adjust the PR based on that, thanks for the quick reply

**Comment by logan-markewich** [comment]
@bwanglzu Thanks for the contribution! Going to close this out though, since we recently switched to the (now excellently maintained) sentence transformers package

**Pull request closed without merging**
