### PR TITLE
Fixing incorrect spacing in prompt templates

### PR DESCRIPTION
**Pull request by jamesbraza**
# Description

I observed:
- Some prompts were missing spaces around line wraps
- 6X repeated text in different places

This PR corrects both, without touching prompt content

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

### CODE REVIEW

**Comment by jamesbraza** [comment]
Hey team, I am hitting one too many `git branch`es rebased on top of each other. Any chance I can get a quick review on this? 🤓

**Comment by Disiok** [comment]
> Hey team, I am hitting one too many `git branch`es rebased on top of each other. Any chance I can get a quick review on this? 🤓

Sure, will take a quick look!

**Review by Disiok — COMMENTED** [review]
Hey @jamesbraza, IMO it's better to repeat text here rather than creating this boilerplate. 
The issues with boilderplate are:
1. makes it more opaque what the template args to the string is.
2. increase coupling across the prompts, which makes modifying individual prompts harder. 

Could you revert those changes, and just keep the spacing fixes?

**Comment by jamesbraza** [comment]
Yeah I can see what you mean. There are also arguments to supporting sharing, since improvements in one prompt can also help others.

Closing this in favor of direct fixes in https://github.com/run-llama/llama_index/pull/8190

**Pull request closed without merging**
