### PR TITLE
Azure CosmosDB NoSql Storage Integrations

### PR DESCRIPTION
**Pull request by aayush3011**
# Description

Storage Integration:
- Chat Store
- Index Store
- KVStore
- Document Store

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by aayush3011** [comment]
@masci @hatianzhang can you please review this PR.

**Comment by masci** [comment]
@aayush3011 this PR is really too large, any chance you can break it down somehow?

**Comment by aayush3011** [comment]
@masci I have divided the original PR into 3.

- [Azure CosmosDB Filtered Vector Search updates](https://github.com/run-llama/llama_index/pull/16175) ( for both NoSql and Mongo vCore)
- [Azure CosmosDB Mongo vCore Storage Integrations](https://github.com/run-llama/llama_index/pull/16176)
- [Azure CosmosDB NoSql Storage Integrations](https://github.com/run-llama/llama_index/pull/16138)

**Comment by aayush3011** [comment]
@masci Friendly ping on the status of the PR.

**Comment by logan-markewich** [comment]
Going to close this PR in favour of the 3 split out ones

**Comment by aayush3011** [comment]
@logan-markewich This is on of the PR which has changes for the Cosmos DB No SQL Storage Integrations. Please can you re-open this PR.

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
