### PR TITLE
GitLab reader integration

### PR DESCRIPTION
**Pull request by jiachengzhang1**
# Description

Implemented gitlab reader by leveraging [python-gitlab](https://python-gitlab.readthedocs.io/en/stable/index.html) to fetch contents from gitlab projects. The integration mimics the existing GitHub reader. Additional parser capabilities are coming soon.

Two separate readers are provided:

1. Repository Reader
2. Issues Reader

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No (new reader)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]
LGTM! Cool!

**Comment by jiachengzhang1** [comment]
@logan-markewich Thank you! The checks failed due to BUILD file issues. I made some changes to hopefully get it fixed.

**Review by Josephrp — APPROVED** [review]
thanks for this cool PR !

**Comment by jiachengzhang1** [comment]
Thanks for getting the dependency issue fixed, I'll look at the `fixture 'mocker' not found` issue after work.

What's your recommendation on the tests? All tests passed when I did `pytest tests` from `llama_index/llama-index-integrations/readers/llama-index-readers-gitlab` locally, maybe I should test it differently.

**Comment by logan-markewich** [comment]
pants can be a little weird in how it figures out dependencies (like me needing to add that mapping) and builds venvs for tests. I don't really expect contributors to figure this out because pants has a bit of a learning curve 😅 I will fix this shortly

**Pull request merged**
