### PR TITLE
update async utils

### PR DESCRIPTION
**Pull request by logan-markewich**
Some small tweaks to our async `run_jobs` function
- Use as_completed wrapped with tqdm instead of tqdm_asyncio
- Allow a description to be passed in

### CODE REVIEW

**Review by nerdai — COMMENTED** [review]
Looks good. Just wondering if the async safety is preserved still.

**Comment by logan-markewich** [comment]
@nerdai Does as_completed have any different behaviour compared to gather? (I wouldn't think so tbh)

**Comment by nerdai** [comment]
> @nerdai Does as_completed have any different behaviour compared to gather? (I wouldn't think so tbh)

I would think not either. It really just boils down to how the tasks/coros are being defined. I just tested to be sure and it looks like we're good to go.

image

**Review by nerdai — APPROVED** [review]

**Comment by logan-markewich** [comment]
Thanks for the test! 🙏🏻

**Pull request merged**
