### PR TITLE
Remove redundant `python_sources` targets

### PR DESCRIPTION
**Pull request by grihabor**
# Description

Pants shows a lot of warnings when running `pants lint ::`
```
17:47:21.69 [WARN] Unmatched globs from llama-index-integrations/readers/llama-index-readers-google:llama-index-readers-google's `sources` field: ["llama-index-integrations/readers/lla
ma-index-readers-google/*.py", "llama-index-integrations/readers/llama-index-readers-google/*.pyi"], excludes: ["llama-index-integrations/readers/llama-index-readers-google/*_test.py",
 "llama-index-integrations/readers/llama-index-readers-google/*_test.pyi", "llama-index-integrations/readers/llama-index-readers-google/conftest.py", "llama-index-integrations/readers/
llama-index-readers-google/test_*.py", "llama-index-integrations/readers/llama-index-readers-google/test_*.pyi", "llama-index-integrations/readers/llama-index-readers-google/tests.py",
 "llama-index-integrations/readers/llama-index-readers-google/tests.pyi"]
``` 
This pr fixes that by removing redundant `python_sources` targets from pants `BUILD` files.

This pr also sets [unmatched_build_file_globs = "error"](https://github.com/run-llama/llama_index/pull/10922/commits/8d38ed52d2e83731c77c3895681416ed84270eaf), so that unmatched globs show up as an error.

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by grihabor** [comment]
@logan-markewich I think the CI is waiting for approval

**Comment by grihabor** [comment]
I'm pretty sure, CI shows an error that doesn't exist
```
InvalidFieldException: llama-index-integrations/llms/llama-index-llms-litellm/BUILD:5: Invalid field value for 'sources'
```
But I'm running `pants tailor --check :: -docs/::` and it shows everything good

**Comment by logan-markewich** [comment]
@grihabor hmmm, yea not sure why it shows up on CI and not for you locally.

I do now this specific file has this in line 5:
```
python_sources(
        interpreter_constraints=["==3.9.*", "==3.10.*"],
)
```

I know you removed some of these already in the top-level BUILD files for packages, maybe this also needs to be removed?

**Comment by grihabor** [comment]
Are you talking about `llama-index-integrations/llms/llama-index-llms-litellm/BUILD`? I haven't even changed it in the pr
```
git diff main --stat | rg llama-index-integrations/llms/llama-index-llms-litellm
```

**Comment by logan-markewich** [comment]
Right, you haven't changed it, but that seems to be the file that CI is complaining about 👀

**Comment by grihabor** [comment]
But there is no line 5 in the file:
```python
$ cat llama-index-integrations/llms/llama-index-llms-litellm/BUILD
poetry_requirements(
    name="poetry",
)
```

**Comment by grihabor** [comment]
I'm pretty sure something is wrong with the CI, the commit hash for https://github.com/run-llama/llama_index/pull/10922/commits/f6aa8677a0ea28f5185b6af322d89d3ae902d347 is wrong:
image

**Comment by grihabor** [comment]
It looks like CI has merged main into my branch and was running checks on this temporary branch. I've merged main and I could see the problem

**Comment by grihabor** [comment]
@logan-markewich Hi! The pr is ready for merge

**Pull request merged**
