### PR TITLE
fix ollama's complete api to utilize generate endpoint

### PR DESCRIPTION
**Pull request by nightosong**
# Description

When using the `llm.complete` interface of Ollama, I found that it actually calls `/api/chat` instead of `/api/generate`. I'm not sure what the initial considerations were for this design. I tried changing it to `/api/generate`, but since Ollama's `is_chat_model` is set to true by default, it may still default to using the `llm.chat` interface in other contexts

Fixes # (issue)

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [X] Yes

## Type of Change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by logan-markewich** [comment]
@nightosong the `generate()` endpoint does not do any prompt formatting (from my understanding), while using `.chat()` ensures that everything will be foramtted properly on Ollama's end

This really simplifies the developer experience 

Is there a specific reason you want to use the `generate()` api?

**Comment by nightosong** [comment]
@logan-markewich As no expert on ollama, I have a few questions:

* Is the generation effect of `/api/chat` the same as that of `/api/generate`?
* ollama officially provides two options, but only one of them seems to be effective.

After reading your comment, I checked the ollama server code. Both `/api/chat` and `/api/generate` call `llm.CompletionRequest`, so theoretically, they should only differ in the prompts passed in. This may solved my first doubt. On the second, I still feel that `generate()` offers a choice, a way to customize the format, rather than forcing me to choose only `chat()`.

**Comment by logan-markewich** [comment]
`generate()` offers a lot more ways for users to shoot themselves in the foot imo 

My understanding is `/api/chat` will automatically format your chat messages into the prompt format the model expects

`/api/generate` will not, and requires you to either passing in extra formatting controls or format yourself ahead of time

I personally don't see the value of supporting the latter -- for 99% of users it will just lead to mistakes that are hard to debug, and for that 1% of users, they might just use Ollama's client directly, subclass the LLM to override, or make a custom llm class

**Comment by nightosong** [comment]
> `generate()` offers a lot more ways for users to shoot themselves in the foot imo
> 
> My understanding is `/api/chat` will automatically format your chat messages into the prompt format the model expects
> 
> `/api/generate` will not, and requires you to either passing in extra formatting controls or format yourself ahead of time (from my understanding)
> 
> I personally don't see the value of supporting the latter -- for 99% of users it will just lead to mistakes that are hard to debug, and for that 1% of users, they might just use Ollama's client directly, subclass the LLM to override, or make a custom llm class

I will carefully consider this issue and only modify the implementation of the `complete()` function series in my code, as I need to differentiate between `chat` and `generate` in my design, while also relying on llamaindex. In some workflow, I need to ensure that the prompts I send to the model remain unchanged.

For most users, when using LlamaIndex, Ollama's LLMMetadata defaults to `is_chat_model=True`, ensuring that users will default to using the  `chat()` based on the LLMMetadata judgment. 
```
    @property
    def metadata(self) -> LLMMetadata:
        """LLM metadata."""
        return LLMMetadata(
            context_window=self.context_window,
            num_output=DEFAULT_NUM_OUTPUTS,
            model_name=self.model,
            is_chat_model=True,  # Ollama supports chat API for all models
            # TODO: Detect if selected model is a function calling model?
            is_function_calling_model=self.is_function_calling_model,
        )
```
However, when I explicitly call `complete()` or `stream_complete()`, the code converts my prompt into a message format, as per follows code,  which may change the prefix of my prompt, and I was unaware of it..
```
def prompt_to_messages(prompt: str) -> List[ChatMessage]:
    """Convert a string prompt to a sequence of messages."""
    return [ChatMessage(role=MessageRole.USER, content=prompt)]
```

**Pull request closed without merging**
