### PR TITLE
Configurable Node ID Generating Function

### PR DESCRIPTION
**Pull request by jordanparker6**
# Description

It would be ideal to be able to customise the node_id generating function. At the moment it is a function that generates a UUIDv4. It would be great to be able to pass a function as an optional parameter to generate an ID of the users design. The function is accepting the chunk index and the source Document. For example, an id function could be `lambda i, doc:, f"{document.id}__{i}"` allowing the user to create a deterministic Node ID process given a fixed document_id and node_parser configuration. This would be useful for upserts on any pipeline re-runs and help avoiding accidental duplicate inserts.

## Type of Change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I have ran all the existing tests and they are passing.

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
@jordanparker6 Thanks for the contribution! I think this is a well-needed change.

Do you mind cleaning up the `mpyp` errors? Just some typing things it looks like
https://github.com/run-llama/llama_index/actions/runs/7241695838/job/19726096350?pr=9574

**Comment by jordanparker6** [comment]
@logan-markewich 

I fixed one of them.

The others are all linked to this weird type error... I don't get where its getting the Callable[[BaseNode], str] type from... Any thoughts? I clearly type annotate Callable[[int, BaseNode], str]].

llama_index/node_parser/interface.py:126: error: Argument "id_func" to "build_nodes_from_splits" has incompatible type "Callable[[BaseNode], str]"; expected "Optional[Callable[[int, BaseNode], str]]"  [arg-type]

**Comment by logan-markewich** [comment]
@jordanparker6 I find you have to use a `Protocol` for most callable type checks. Still haven't figured out exactly when it's needed, but it helped here

**Review by logan-markewich — APPROVED** [review]

**Comment by jordanparker6** [comment]
@logan-markewich ahhh ok. I'll read up on the Protocol type. Learn something new.

**Pull request merged**
