### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by Athulmathew01**
pinning a minimum version of the dependency in the pyproject.toml file

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]
Thanks!

**Comment by michaelfeil** [comment]
@Athulmathew01 I think you should run `poetry lock --no-update` first, to resolve the package. 

Optionally, it would be great to add it to the section, such that `pip install llama-index[gradientai]` is possible

**Review by Athulmathew01 — COMMENTED** [review]
I hope it's ok now.

**Comment by michaelfeil** [comment]
@Athulmathew01 Saw you are running poetry=1.7.1
```bash
pip install poetry==1.6.1 pre-commit
pre-commit install
poetry lock --no-update
pre-commit run --all-files
git commit -m "this should pass"
```

**Comment by Athulmathew01** [comment]
Thanks @michaelfeil  for helping me. I am just new to this.

**Pull request merged**
