### PR TITLE
Add: Async upserting for Qdrant vector store

### PR DESCRIPTION
**Pull request by KennyStryker**
# Description

Added async upserting feature for Qdrant vector store:
* Implemented `async_add` method to QdrantVectorStore.
* Update the qdrant demo notebook to demostrate usage of async and grpc upserting.
* Minor typo fix in ChromaDB demo notebook.

## Type of Change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [X] Added existing unit/integration tests
- [X] Updated the demo notebook to show its usage.

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by Disiok** [comment]
Thanks for the contribution! Will take a closer look shortly. 

In the meanwhile, would you also update `docs/core_modules/data_modules/storage/vector_stores.md` to check the async support for Qdrant?

**Comment by KennyStryker** [comment]
> Thanks for the contribution! Will take a closer look shortly.
> 
> In the meanwhile, would you also update `docs/core_modules/data_modules/storage/vector_stores.md` to check the async support for Qdrant?

Hi,

I originally thought about it, but I wasn't sure since this PR only implements async collection creation and insertion, not querying or deletions. Would something like `partial` be allowed? If not, please let me know, I'll check async support for Qdrant on docs.

**Comment by KennyStryker** [comment]
Implemented async version of querying as well. `aquery`. Now LlamaIndex fully supports async operations with Qdrant vector store.

`docs\examples\vector_stores\QdrantIndexDemo.ipynb` has also been updated and now includes usage example for both insertion and querying.

**Comment by KennyStryker** [comment]
Hi @Disiok, have you had any chance to look at it?

**Comment by Disiok** [comment]
> Hi @Disiok, have you had any chance to look at it?

Looks great! Thanks so much for the contribution and adding to the doc. Merging now.

**Pull request merged**
