### PR TITLE
Prem AI LlamaIndex integration (migrating PR from org account to personal account)

### PR DESCRIPTION
**Pull request by Anindyadeep**
# Description

This PR adds the integration with [PremAI's](https://www.premai.io/) prem-sdk with llama-index. User can now access to deployed models (llms/embeddings) and use it with llama-index's retrieval ecosystem. 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update (already provided)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Added new unit/integration tests
- [X] Added new notebook (that tests end-to-end)
- [X] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added Google Colab support for the newly added notebooks.
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by Anindyadeep** [comment]
Thanks @logan-markewich for the merge, but after this, when I am trying to see if things worked out or not, I am seeing this:

```python
>>> import llama_index.llms.premai
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'llama_index.llms.premai'
```

**Comment by logan-markewich** [comment]
@Anindyadeep you'll have to install first 

`pip install llama-index-llms-premai`

**Comment by Anindyadeep** [comment]
> @Anindyadeep you'll have to install first
> 
> `pip install llama-index-llms-premai` `pip install llama-index-embeddings-premai`

I see, but doing this also did not work

```python

(venv) ➜  oss pip install llama-index-llms-premai
ERROR: Could not find a version that satisfies the requirement llama-index-llms-premai (from versions: none)
ERROR: No matching distribution found for llama-index-llms-premai
```

**Comment by logan-markewich** [comment]
Try now. It must have attempted to publish when pypi was having issues the other day

**Comment by Anindyadeep** [comment]
> pip install llama-index-embeddings-premai

Hey, thanks for the update, llms is working but not the embeddings

```bash
(venv) ➜  workspace pip install llama-index-embeddings-premai
ERROR: Could not find a version that satisfies the requirement llama-index-embeddings-premai (from versions: none)
ERROR: No matching distribution found for llama-index-embeddings-premai
```

**Comment by logan-markewich** [comment]
Embeddings published

**Comment by Anindyadeep** [comment]
> pip install llama-index-embeddings-premai

Awesome, thanks @logan-markewich :)

**Pull request merged**
