### PR TITLE
Add tool usage support with text-generation-inference integration from Hugging Face

### PR DESCRIPTION
**Pull request by cyril-k**
# Description

Integration of the latest functionality from `text-generation-inference` (starting from v2.0.1) which allows to use tools with proper `tool_name` resolution.
Created a new `TextGenerationInference` class which builds upon `text-generation` classes (`Client` and `AsyncClient`) and integrates tools in a manner similar to OpenAI and MistralAI.

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Updated notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
@cyril-k it looks like the associated PR for huggingface got merged. Does that mean this works now?

**Comment by cyril-k** [comment]
> @cyril-k it looks like the associated PR for huggingface got merged. Does that mean this works now?

Hi @logan-markewich,
Will test again with new TGI container and update this PR.

**Comment by cyril-k** [comment]
> @cyril-k it looks like the associated PR for huggingface got merged. Does that mean this works now?

I tested with new TGI v2.0.1, the issue with `tool_name` appears to be resolved!

**Review by logan-markewich — APPROVED** [review]

**Comment by mphipps2** [comment]
Hi @logan-markewich and @cyril-k, Cyril mentioned an "issue with tool_name". What was that?

Because I'm having an issue when calling ChatResponse from TextGenerationInferece where I get a Pydantic validation error due to tool_calls and role being empty. 

File "/usr/local/lib/python3.9/site-packages/text_generation/client.py", line 186, in _chat_stream_response
response = ChatCompletionChunk(**json_payload)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ChatCompletionChunk
choices.0.delta.tool_calls
Field required [type=missing, input_value={'role': 'assistant', 'content': ' Why'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.6/v/missing

Which is breaking due to there not being a tool_calls key inside the 'delta' dict:

It's breaking due to the json payload missing the tool_calls (and on the token) the role:
post payload: {'id': '', 'object': 'text_completion', 'created': 1716232578, 'model': '/hf_hub/Mixtral-8x22B-Instruct-v0.1', 'system_fingerprint': '2.0.2-xxx, 'choices': [{'index': 0, 'delta': {'role': 'assistant', 'content': ' Why'}, 'logprobs': None, 'finish_reason': None}]}

I'm able to fix this by updating TGI's ChoiceDelta class inside types.py withg role and tool_calls defaulted to None:

```
class ChoiceDelta(BaseModel):
  role: str = None
  content: Optional[str] = None
  tool_calls: Optional[ChoiceDeltaToolCall] = None
```

But trying to understand if this is a bug on TGI's side or something that others have working somehow? Any help, really appreciated

**Comment by Inigo-13** [comment]
> > @cyril-k it looks like the associated PR for huggingface got merged. Does that mean this works now?
> 
> Hi @logan-markewich, I tested with new TGI v2.0.1, the issue with `tool_name` appears to be resolved!



Hi there!

It seems like there is a pydantic validation issue when retrieving the metadata property of these new TGI instances. This is related to a new problem through the inheritance chain.

- [the self.model_name reference of the Pydantic instance is never set and the LLMMetadata model raises validation exception](https://github.com/run-llama/llama_index/pull/12471/files#diff-2e8e34af665323418f6866ac92446682885718fbe7b15f3224b28ae1388b1488R838)
- This is because [the new \_\_init__ overrides the BaseModel \_\_init__ with a key 'model',](https://github.com/run-llama/llama_index/pull/12471/files#diff-2e8e34af665323418f6866ac92446682885718fbe7b15f3224b28ae1388b1488R818) **which actually does not match** the [actual 'model_name' pydantic parameter](https://github.com/run-llama/llama_index/pull/12471/files#diff-2e8e34af665323418f6866ac92446682885718fbe7b15f3224b28ae1388b1488R690).
- As a result, LLMMetadata raises validation error since 'None' is not valid (and never set).

**Pull request merged**
