### PR TITLE
Box reader integration

### PR DESCRIPTION
**Pull request by chetanchoudhary-calsoft**
Integrating Box Reader satsifying ResourcesReaderMixin, FileSystemReaderMixin to be used by llamacloud

### CODE REVIEW

**Comment by barduinor** [comment]
Hi @chetanchoudhary 

I'm a dev rel at Box.com, and we also submitted a [PR](https://github.com/run-llama/llama_index/pull/14685) for a Box reader.

Not sure what the LLama-Index folks will do in this situation, but what ever it is we at Box dev rel are open to collaborate, if you're interested.

If you want to check the progress so far, take a look at our [branch](https://github.com/box-community/llama_index/tree/box-reader).

Cheers

**Comment by Disiok** [comment]
> Hi @chetanchoudhary
> 
> I'm a dev rel at Box.com, and we also submitted a [PR](https://github.com/run-llama/llama_index/pull/14685) for a Box reader.
> 
> Not sure what the LLama-Index folks will do in this situation, but what ever it is, we at Box dev rel, are open to collaborate, if you're interested.
> 
> If you want to check the progress so far, take a look at our [branch](https://github.com/box-community/llama_index/tree/box-reader).
> 
> Cheers

Hey @barduinor great to meet! We'd love to coordinate the two streams of work and get this merged in asap. Could you shoot me an email at simon@runllama.ai to setup a quick chat?

**Comment by chetanchoudhary-calsoft** [comment]
> Hi @chetanchoudhary
> 
> I'm a dev rel at Box.com, and we also submitted a [PR](https://github.com/run-llama/llama_index/pull/14685) for a Box reader.
> 
> Not sure what the LLama-Index folks will do in this situation, but what ever it is, we at Box dev rel, are open to collaborate, if you're interested.
> 
> If you want to check the progress so far, take a look at our [branch](https://github.com/box-community/llama_index/tree/box-reader).
> 
> Cheers

Hey @barduinor , if this one gets merged, we can definitely collaborate together to integrate the additional features in you PR.

**Comment by logan-markewich** [comment]
I think assuming we can port the mixins used here to #14685 then we can go with that PR, since its a bit more comprehensive 👍🏻

**Comment by logan-markewich** [comment]
Closing in favour of #14685 -- Thank you @chetanchoudhary-calsoft for the implementation, it definitely helped to expand the other PR! ❤️

**Comment by chetanchoudhary** [comment]
> Closing in favour of #14685 -- Thank you @chetanchoudhary-calsoft for the implementation, it definitely helped to expand the other PR! ❤️ 

Thanks @logan-markewich and @barduinor , I am happy to be a part of it 🙂

**Comment by barduinor** [comment]
@chetanchoudhary-calsoft , I wanted to thank you for your interest in the box connector, and also to mention that I saw great ideas in your code that are not implemented yet, like the handling of the API limits or the chunked downloads.

Those would be very welcome additions.
Cheers

**Comment by chetanchoudhary** [comment]
> @chetanchoudhary-calsoft , I wanted to thank you for your interest in the box connector, and also to mention that I saw great ideas in your code that are not implemented yet, like the handling of the API limits or the chunked downloads.
> 
> Those would be very welcome additions. Cheers

Thanks @barduinor , I will definitely contribute to new BoxReader.

**Pull request closed without merging**
