### PR TITLE
Add GPT4-V and Microsoft Table transformer experiments with PDF which has tables.

### PR DESCRIPTION
**Pull request by ravi03071991**
# Description

This PR shows experiments of GPT4-V and Microsoft Table transformer with PDF which has tables.

Merge this example https://github.com/run-llama/llama_index/pull/9235 with this pr
## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by jerryjliu — APPROVED** [review]
This is awesome. Some very minor nits but approving to unblock. Excited to land this tmrw morning: 
- In section 1, you define a `text_store` but that is never used 
- the query in section 4 is triple quotes, which means you're introducing unnecessary tabs in each line besides the first

should be like this 
```
query = f"""Based on the following table information extracted, answer the query: \n

TABLE INFORMATION:

{table_text}


Query:

Compare llama2 with llama1?
            """
```

**Comment by jerryjliu** [comment]
also, can we add a link somewhere in docs? can say https://docs.llamaindex.ai/en/latest/use_cases/multimodal.html for now

**Comment by jerryjliu** [comment]
also to verify, table extraction happens after CLIP-based retrieval right? did you try retrieving via CLIP vs. retrieving via summarized text?

**Comment by ravi03071991** [comment]
> This is awesome. Some very minor nits but approving to unblock. Excited to land this tmrw morning:
> 
> * In section 1, you define a `text_store` but that is never used
> * the query in section 4 is triple quotes, which means you're introducing unnecessary tabs in each line besides the first
> 
> should be like this
> 
> ```
> query = f"""Based on the following table information extracted, answer the query: \n
> 
> TABLE INFORMATION:
> 
> {table_text}
> 
> 
> Query:
> 
> Compare llama2 with llama1?
>             """
> ```

Will update the string query/ prompt template.

**Comment by jerryjliu** [comment]
> > also to verify, table extraction happens after CLIP-based retrieval right? did you try retrieving via CLIP vs. retrieving via summarized text?
> 
> Nope. We concentrated on experimenting with treating PDFs as images and using GPT4-V to answer the queries.
> 
> Also, do you mean summarizing text with GPT4-V?

yeah no worries

**Comment by hatianzhang** [comment]
for the 2nd experiment, if GPT4V cannot detect/parse table from pdf page. We will let GPT4v summarize the whole page as a fall back

**Comment by linminhtoo** [comment]
hi, i can't run this notebook example
https://github.com/run-llama/llama_index/blob/main/docs/examples/multi_modal/multi_modal_pdf_tables.ipynb

in the part when we use `qdrant_client` to initialise the text & image store and then create the `MultiModalVectorStoreIndex`, I get the error `ValueError: Collection text_collection not found` 

please see this issue for full details https://github.com/qdrant/qdrant/issues/3289 

is this due to a version mismatch in llama-index and/or qdrant_client ?  what version should I be using?

**Pull request merged**
