### PR TITLE
feat: Support for api_version and Azure AI model inference service

### PR DESCRIPTION
**Pull request by santiagxf**
# Description

Introducing support for `api_version` parameter in case the user needs to override the default version used in the client. It was possible before by using `client_kwards` but now it's more transparent by indicating it on the constructor. It also introduces support for the [Azure AI model inference service](https://aka.ms/aiservices/inference).

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Your pull-request will likely not be merged unless it is covered by some form of impactful unit testing.

- [x] I added new unit tests to cover this change
- [ ] I believe this change is already covered by existing unit tests

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by santiagxf** [comment]
@masci I'm having troubles on getting the package `aiohttp` installed for tests, which is the reason why the build is failing. Any pointer?

**Comment by masci** [comment]
@santiagxf it took me a while but I managed to reproduce locally, not sure what's the problem, I'll report here my findings

**Comment by masci** [comment]
I tried to convice Pants that `aiohttp` is required in several different ways without success. Resorting to add a useless `import aiohttp` in the tests module that seems to work locally.

**Review by masci — APPROVED** [review]
LGTM!

**Comment by santiagxf** [comment]
Thanks for the help @masci !

**Pull request merged**
