### PR TITLE
Google readers integrations doc and drive updates

### PR DESCRIPTION
**Pull request by MeTaNoV**
# Description

- Add missing README.md for all readers folder lost during the last migration from llamahub
- Add `query_string` in Google Drive Reader
- Some others minor fixes

## Type of Change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by hatianzhang — COMMENTED** [review]
looks amazing!

**Comment by MeTaNoV** [comment]
> looks amazing!

Thanks, I was not able to lint / build locally, let me check at the errors... :)

**Comment by MeTaNoV** [comment]
@hatianzhang it looks like the toml part failed, might be due to me adding:

```
[tool.llamahub.class_contributors]
GoogleDriveReader = ["metanov"]
```

should I remove that part ?

**Comment by nerdai** [comment]
> @hatianzhang it looks like the toml part failed, might be due to me adding:
> 
> ```
> [tool.llamahub.class_contributors]
> GoogleDriveReader = ["metanov"]
> ```
> 
> should I remove that part ?

please do not remove that part, otherwise it won't show up in our llamahub.ai webpage.

Please instead do the following:

```
make lint
git add .
git commit -m "lint"
git push origin <your-branch-name>
```

**Comment by MeTaNoV** [comment]
thx @logan-markewich for the updates!

**Pull request merged**
