### PR TITLE
Feature/lm format enforcer integration

### PR DESCRIPTION
**Pull request by noamgat**
# Description

This PR adds support for [lm-format-enforcer](https://github.com/noamgat/lm-format-enforcer) to llama_index. 

image

I started work on this after a discussion on Discord.
The library is comparable to guidance (and the integration + example notebook is similar) but has very different LLM backend coverage - it supports local LLMs - `HuggingFaceLLM` and `LlamaCPP`. It also takes a different technological approach which reduces hallucinations on some LLMs.

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

I looked at the unit tests, and the ones for HuggingFaceLLM and LlamaCPP avoid using the actual backbone and mock it away. This would make all of the contributions of the classes here redundant, so I think an end-to-end notebook is the correct way to test.

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by Disiok** [comment]
> How should the documentation change? Is it autogenerated from notebooks / classes or do I need to add an entry?
Is there a good way to create unit tests, if the core of the functionality relies on real LlamaCPP / HuggingFaceLLM models?
[lm-format-enforcer](https://github.com/noamgat/lm-format-enforcer) also supports Regular Expression enforcing, but this integration only covers the JSON Schema use case. Where would be the best place to add regex support?


Thanks for the contribution! 
* documentation consists of example notebooks, which we place under ` docs/examples`, and additional documentation pages (written in markdown or sphinx files). To make an example notebook visible, it needs to be linked into a doc page.
* we typically just use a mock LLM with some mock output.
* cool! will take a closer look at the regex enforcing stuff. we currently only have structured output interface as defined by json schema (via pydantic), but we can create a similar abstraction for regex if this works well.

**Comment by noamgat** [comment]
Thanks for the feedback!
Updates:

- I refactored the low level parts of the `LMFormatEnforcerPydanticProgram` implementation to a utils file. This makes it easier to use LMFormatEnforcer directly in LlamaIndex without new classes.
- This allowed me to elegantly integrate with the regular expression engine of LMFormatEnforcer, and create a notebook showcasing it.
- I created a doc page with the essence of both examples, and links to the respective notebook.
- I created a test for the Program class that mocks the entire LLM stack. I saw there are no tests for `LlamaCpp` or `HuggingfaceLLM` classes, which are the backbone of the `utils` functions I added.

I think its merge-worthy now, will be happy to get feedback!

**Comment by noamgat** [comment]
I saw that the lint run failed. Pushed a small commit to fix it. Don't know why my local lint runs didn't catch it :(

**Review by Disiok — APPROVED** [review]
This is fantastic an definitely solve a pretty important user need! Thanks for getting this in.

I'd love to explore how to make the regex forcing feature more of a first class citizen in llamaindex as next step as well.

**Pull request merged**
