### PR TITLE
Prem AI LlamaIndex integration

### PR DESCRIPTION
**Pull request by Anindyadeep**
# Description

This PR adds the integration with [PremAI's](https://www.premai.io/) prem-sdk with llama-index. User can now access to deployed models (llms/embeddings) and use it with llama-index's retrieval ecosystem. 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update (already provided)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Added new unit/integration tests
- [X] Added new notebook (that tests end-to-end)
- [X] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added Google Colab support for the newly added notebooks.
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by hatianzhang — APPROVED** [review]

**Comment by hatianzhang** [comment]
@Anindyadeep could you fix the unit test

**Comment by Anindyadeep** [comment]
> @Anindyadeep could you fix the unit test

Hey, upon seeing the error, I saw that there was a problem in BUILD files. I did resolved that and also did the lint checks. Hopefully it should work now.

**Comment by Anindyadeep** [comment]
> > @Anindyadeep could you fix the unit test
> 
> Hey @hatianzhang , upon seeing the error, I saw that there was a problem in BUILD files. I did resolved that and also did the lint checks. Hopefully it should work now.

Hi @hatianzhang, I saw the error message in the Unit Testing, but I was't able to resolve this one. Can you help me in pointing out. Thanks

**Comment by hatianzhang** [comment]
@logan-markewich do you know why the unit tests failed. the pyproject.toml lgtm

**Comment by logan-markewich** [comment]
@hatianzhang just incorrect pants build files. Will fix in a bit

**Comment by Anindyadeep** [comment]
> @hatianzhang just incorrect pants build files. Will fix in a bit

I see, let me know when it is fixed, I would merge those changes from main

**Comment by logan-markewich** [comment]
Oh, I can't make changes in this PR 😢

**Comment by logan-markewich** [comment]
Can you [install pants](https://www.pantsbuild.org/2.19/docs/getting-started/installing-pants) and run `pants tailor ::` ? It will edit/create some files, just add the files that it creates/edits in these new folders, ignore anything else it does

**Comment by Anindyadeep** [comment]
> Can you [install pants](https://www.pantsbuild.org/2.19/docs/getting-started/installing-pants) and run `pants tailor ::` ? It will edit/create some files, just add the files that it creates/edits in these new folders, ignore anything else it does

Yes, I did and I got this error:

```
(venv) ➜  llama_index git:(main) pants tailor ::
09:45:26.34 [ERROR] 1 Exception encountered:

Engine traceback:
  in `tailor` goal

IntrinsicError: Unmatched glob from poetry_requirements(address="llama-index-integrations/embeddings/llama-index-embeddings-premai/llama_index/embeddings/premai:poetry", description=None, module_mapping=FrozenDict({}), overrides=None, source=pyproject.toml, tags=None, type_stubs_module_mapping=FrozenDict({}))'s field `source`: "llama-index-integrations/embeddings/llama-index-embeddings-premai/llama_index/embeddings/premai/pyproject.toml"

Do the file(s) exist? If so, check if the file(s) are in your `.gitignore` or the global `pants_ignore` option, which may result in Pants not being able to see the file(s) even though they exist on disk. Refer to https://www.pantsbuild.org/v2.19/docs/troubleshooting#pants-cannot-find-a-file-in-your-project.

(venv) ➜  llama_index git:(main) git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

**Comment by Anindyadeep** [comment]
Hi @logan-markewich @hatianzhang, I am closing this PR, since I migrated everything to this #11954 PR. Hope now it would be easier for us to re-iterate and hopefully merge. 

Thanks

**Pull request closed without merging**
