### PR TITLE
Add google colab support for notebooks

### PR DESCRIPTION
**Pull request by ravi03071991**
# Description

PR adds support to open the notebooks in Google Colab so that it would be easier for developers to run through the notebooks.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [X] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Disiok — APPROVED** [review]
Ooooh ya this is a good idea. Thanks @ravi03071991 !

Question, is the plan here to add this to every single notebook we have in the repo?

**Comment by ravi03071991** [comment]
> Ooooh ya this is a good idea. Thanks @ravi03071991 !
> 
> Question, is the plan here to add this to every single notebook we have in the repo?

Yeah, I believe this will be a valuable experience for developers. I will begin with the most commonly used notebooks and eventually expand to include all of them. Additionally, it would be beneficial to have Google Colab support for any new notebooks we introduce moving forward.

**Comment by Disiok** [comment]
hey @ravi03071991, are still planning to wrap up and land this?

**Comment by ravi03071991** [comment]
> hey @ravi03071991, are still planning to wrap up and land this?

@Disiok I will complete it in the next 2-3 days.

**Comment by ravi03071991** [comment]
@Disiok The checks aren't running, and I don't have permission to resolve the conflicts. Can you assist me with this?

**Comment by ravi03071991** [comment]
@Disiok completed the support of google collab for notebooks. Please review and merge.

**Comment by Disiok** [comment]
This is massive! Amazing work@ravi03071991

**Pull request merged**
