### PR TITLE
Updated AzureCosmosDBMongoDBVectorSearch to Pydantic Vector Store base class

### LINKED ISSUE #11614: AzureCosmosDBMongoDBVectorSearch class is imcompatible with the IngestionPipeline[Bug]:
### Bug Description

Similar to issues https://github.com/run-llama/llama_index/issues/10688 and https://github.com/run-llama/llama_index/pull/10698, the AzureCosmosDBMongoDBVectorSearch class is imcompatible with the IngestionPipeline.

The error that I get is:

ValidationError: 1 validation error for IngestionPipeline
vector_store
  value is not a valid dict (type=type_error.dict)

The problem is described in more detail for different vector stores here: https://github.com/run-llama/llama_index/issues/10688.

### Version

0.10.15

### Steps to Reproduce

azure_cosmos_store = AzureCosmosDBMongoDBVectorSearch(
    mongodb_client=mongodb_client,
    db_name="some_db",
    collection_name="some_collection",
)
pipeline = IngestionPipeline(transformations=transformations, vector_store=azure_cosmos_store)

### Relevant Logs/Tracbacks

_No response_

### PR DESCRIPTION
**Pull request by shadyelgewily-slimstock**
# Description

Similar to issues https://github.com/run-llama/llama_index/issues/10688 and https://github.com/run-llama/llama_index/pull/10698, the AzureCosmosDBMongoDBVectorSearch class is imcompatible with the IngestionPipeline. This PR changes the base class of AzureCosmosDBMongoDBVectorSearch from VectorStore to BasePydanticVectorStore in order to make it usable in an IngestionPipeline.

Fixes  #11614

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] I stared at the code and made sure it makes sense
- [x] With the changes applied in my project, I managed to store an index in AzureCosmosDBMongoDBVectorSearch using IngestionPipeline(transformations=transformations, vector_store=azure_cosmos_store)

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I ran `make format; make lint` to appease the lint gods

# Some questions in order to test my changes

I have followed the setup description in contributing.md to test the project locally. However, I run into the following issues:

- Pytest is not part of the poetry environment. I have to add it to the poetry environment separately in order to run pytest with the proper dependencies. I'm probably not doing it right, what is the recommended way to run the tests?
- When running pytest on test_vector_stores_azurecosmosmongo.py, mongodb package is not installed. In my project, I resolved this by installing llama-index-vector-stores-azurecosmosmongo as a separate package. What is the recommended way to test integrations/integrated functionality using poetry?
- Make is not part of the poetry environment, nor could I find any documentation on how to set this up for llama_index.

If a maintainer can help me setup the testing environment in poetry/point me in the right direction, then I can run the tests on my changes to ensure nothing broke.

### CODE REVIEW

**Review by logan-markewich — COMMENTED** [review]
Can you bump the version for the package in the pyproject.toml file of this package?

**Comment by shadyelgewily-slimstock** [comment]
@logan-markewich I bumped the version of azurecosmosmongo to 0.1.3. Should I also poetry lock (--no-update) to update the lock file?

**Comment by logan-markewich** [comment]
@shadyelgewily-slimstock no need, CICD will handle that. Thanks!

**Review by logan-markewich — APPROVED** [review]

**Comment by shadyelgewily-slimstock** [comment]
Seems like the linter has failed. Before committing the changes, I ran the command:

poetry run pre-commit install

and when committing, various automated checks were running. This resulted in a file that was automatically updated and after gid add and git commit, all automated checks in pre-commit were succesful.

@logan-markewich did I forget a step?

**Comment by logan-markewich** [comment]
`make lint` should be making any linting changes as needed, but you need to add the changes -- one sec, I can do it as well :)

**Pull request merged**
