### PR TITLE
[wip] force openai structured output

### PR DESCRIPTION
**Pull request by jerryjliu**

### CODE REVIEW

**Comment by jerryjliu** [comment]
note: still working on this, running into weird openai tool calling errors

**Comment by nerdai** [comment]
> note: still working on this, running into weird openai tool calling errors

is there a quick unit test that would make sense to add from these errors?

**Review by logan-markewich — APPROVED** [review]
This looks good to me, and seems to be working! Will need to publish core before publishing the updated llm and agent packages

**Comment by matthiaskern** [comment]
@jerryjliu @logan-markewich would you be open to a PR that would also allow this for anthropic models?

**Comment by logan-markewich** [comment]
@matthiaskern go for it :)

**Pull request merged**
