### PR TITLE
fix(graph_stores/nebulagraph):Modify the openCypher syntax to nGql st…

### PR DESCRIPTION
**Pull request by Gevygg**
…atements to adapt to the latest version of nebula

# Description

The original nebulastore encountered a openCypher syntax error when using Nebula 3.4.0 due to Nebula openCypher syntax limitations and needs to be changed to Nebula's nGQL syntax
Fixes # (issue)

## Type of Change

Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

using Nebulastore for text2cipher operation，Initialize KnowledgeGraphQueryEngine and query

# Suggested Checklist:

 I have performed a self-review of my own code

### CODE REVIEW

**Comment by logan-markewich** [comment]
@wey-gu do you mind double checking this change? I'm unsure of the implications

**Comment by wey-gu** [comment]
> @wey-gu do you mind double checking this change? I'm unsure of the implications 

Sure I'll collaborate this change tomorrow morning!

@Gevygg thanks for the contribution! Will review/co-author tomorrow morning.

Thanks, Wey

**Comment by wey-gu** [comment]
Dear @Gevygg ,

Sorry for the implementation initially not supported NebulaGraph older than 3.4.0. I was actually fixing this in #7204 if you look into the change on nebulagraph.py under graph store.

The current implementation is great(nicely composed pipeline with LOOKUP and GO❤), while it involves the requirement of the **index** on edges, thus is invasive to the existing KG. I actually was pushing on asking LOOKUP to decouple the requirement of an index in the community but it won't help on older version of NebulaGraph anyway, thus, the mitigation that balanced those trade-offs were using 2-shots queries.

> note, index has its cost in writing time, and introducing indexes of all edges just to enable text2cypher may be too expensive.

```diff
commit 1148933eab39f9ad3b7965f8a393c4544438451d
Author: Wey Gu <weyl.gu@gmail.com>
Date:   Wed Aug 16 08:53:54 2023 +0800

    nebulagraph: impl. as #7204, w/o dep on index
    
    Change the implementation to 2-shots MATCH
    W/O requiring LOOKUP, the nGQL that depedent
    on NebulaGraph Index

diff --git a/llama_index/graph_stores/nebulagraph.py b/llama_index/graph_stores/nebulagraph.py
index a8e66ee8..cd165e7e 100644
--- a/llama_index/graph_stores/nebulagraph.py
+++ b/llama_index/graph_stores/nebulagraph.py
@@ -16,12 +16,18 @@ WAIT_MAX_SECONDS = 10
 logger = logging.getLogger(__name__)
 
 
-rel_query = Template(
+rel_query_sample_edge = Template(
     """
-LOOKUP ON $edge_type 
-YIELD src(edge) AS srcVid |
-GO FROM $$-.srcVid OVER $edge_type 
-        YIELD "(:" + tags($$^)[0] + ")-[:$edge_type]->(:" + tags($$$$)[0] + ")" AS rels | limit 1
+MATCH ()-[e:`$edge_type`]->()
+RETURN [src(e), dst(e)] AS sample_edge LIMIT 1
+"""
+)
+
+rel_query_edge_type = Template(
+    """
+MATCH (m)-[:`$edge_type`]->(n)
+  WHERE id(m) == "$src_id" AND id(n) == "$dst_id"
+RETURN "(:" + tags(m)[0] + ")-[:$edge_type]->(:" + tags(n)[0] + ")" AS rels
 """
 )
 
@@ -523,8 +529,16 @@ class NebulaGraphStore(GraphStore):
             edge_types_schema.append(edge_schema)
 
             # build relationships types
+            sample_edge = self.execute(
+                rel_query_sample_edge.substitute(edge_type=edge_type_name)
+            ).column_values("sample_edge")
+            if len(sample_edge) == 0:
+                continue
+            src_id, dst_id = sample_edge[0].cast()
             r = self.execute(
-                rel_query.substitute(edge_type=edge_type_name)
+                rel_query_edge_type.substitute(
+                    edge_type=edge_type_name, src_id=src_id, dst_id=dst_id
+                )
             ).column_values("rels")
             if len(r) > 0:
                 relationships.append(r[0].cast())
```

What do you think, please? If it's OK, I would like to make this change in this PR to co-author with you.

Could you please help add me(weyl.gu [at] gmail.com) to your fork repo to enable my remote push?

Thanks!

**Comment by logan-markewich** [comment]
Going to close this one out for now, its quite outdated at this point

If its still an issue, please raise an updated PR

Sorry for letting this one sit for so long!

**Pull request closed without merging**
