### PR TITLE
Add quiet flag to UpstashVectorDemo

### PR DESCRIPTION
**Pull request by MeshanKhosla**
# Description

Simple change to clean up UpstashVectorDemo to not show `Requirement already satisfied` on pip install

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by hatianzhang — APPROVED** [review]

**Comment by MeshanKhosla** [comment]
@logan-markewich @nerdai  Looks like the demo file got deleted somehow, maybe related to https://github.com/run-llama/llama_index/pull/10537

Should I make a separate PR to recreate it or can it be fixed through the conflict editor?

**Comment by nerdai** [comment]
> @logan-markewich @nerdai Looks like the demo file got deleted somehow, maybe related to #10537
> 
> Should I make a separate PR to recreate it or can it be fixed through the conflict editor?

Sorry about that @MeshanKhosla! Let me take a stab at bringing it back. Will let you know if we need you to resubmit it.

**Comment by nerdai** [comment]
@MeshanKhosla here's the PR for adding back the notebook. I went ahead and ran our upgrade script on it so that it can work with v0.10. Please take a look and let me know if there are any issues - I hope there aren't any. 😊

**Comment by MeshanKhosla** [comment]
> @MeshanKhosla here's the [PR](https://github.com/run-llama/llama_index/pull/10596) for adding back the notebook. I went ahead and ran our upgrade script on it so that it can work with v0.10. Please take a look and let me know if there are any issues - I hope there aren't any. 😊

@nerdai Thanks! The file looks good, but the changes in this current PR aren't added (adding the quiet flag and deleting the `Requirements already satisfied ...` comments. The correct demo file is here if you want to copy it:
https://github.com/run-llama/llama_index/blob/ae1a09633addcc739a758a23b0e32d17586afedf/docs/examples/vector_stores/UpstashVectorDemo.ipynb

**Comment by nerdai** [comment]
@MeshanKhosla  ohh right I guess this PR didn't get merged before migration. No worries. I'll add the latest changes to the new PR.

**Comment by MeshanKhosla** [comment]
> @MeshanKhosla ohh right I guess this PR didn't get merged before migration. No worries. I'll add the latest changes to the new PR.
> 
> UPDATE: this is done now! :)

Sweet, thank you very much. I'll close this PR and it would be great if you can merge that one!

**Comment by nerdai** [comment]
done! thanks :)

**Pull request closed without merging**
