### PR TITLE
Fix bm25 retriever

### PR DESCRIPTION
**Pull request by logan-markewich**
# Description

BM25 does not do any handling for stopwords, so we should be removing stopwords ourselves.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by hatianzhang** [comment]
nice, are we also applying stemmer?

**Review by hatianzhang — APPROVED** [review]

**Comment by logan-markewich** [comment]
not at the moment, but we should be

**Comment by hatianzhang** [comment]
for stemmer, stopwords, we could add an option for users/us to enable or disable

**Comment by logan-markewich** [comment]
@hatianzhang I think people can just override the tokenizer function and pass their own in if they want. It's not clear to me (and likely to users) why they might disable stemming

**Pull request merged**
