### PR TITLE
fix: :bug: Fix Bedrock Converse's tool use blocks, when there are multiple consecutive function calls

### PR DESCRIPTION
**Pull request by AndreCNF**
# Description

Sometimes `BedrockConverse` would fail when trying to load a chat history that had consecutive function calls. This is because function calls weren't being checked in messages that are tool results.

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [X] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [X] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added Google Colab support for the newly added notebooks.
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by nerdai — COMMENTED** [review]
I think this makes sense @AndreCNF. Thanks for contributing fix. Am wondering if possible to either add a brief comment in the code regarding the error case we're trying to remedy, or perhaps even a better a small unit test for this.

**Comment by AndreCNF** [comment]
> Am wondering if possible to either add a brief comment in the code regarding the error case we're trying to remedy, or perhaps even a better a small unit test for this.

I don't think that we can really unit test this as it requires AWS credentials to run (but do share if there's a way to mock AWS' converse API).

I'll add a comment though 🔜

**Comment by AndreCNF** [comment]
I've added a new comment. @nerdai What do you think?

**Review by logan-markewich — APPROVED** [review]
Looks good to me :)

**Pull request merged**
