### PR TITLE
[Draft] Google Review MM Relevance Ranking Example

### PR DESCRIPTION
**Pull request by hatianzhang**
# Description

Using Google Store review dataset build a MM RAG.
1. Download google review data and sample some rows
2. Build MM index
3. Retrieve images and texts for a text query
4. simple score fusion
5. Generate relevance label from GPT4v 
6. Train simple ltr model 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
This looks good to me -- but I almost wonder if the fusion thing should be built into the retriever itself?

**Review by jerryjliu — COMMENTED** [review]
probably needs a bit more polish before landing:
- let's fix the spelling mistakes in the notebook (*restaurant, *images)
- "Count how many unique stores [are in] in our dataset"
- The title doesn't mention Google Product Reviews at all - it probably should?
- Instead of outlining all the steps, it would be great to add some higher-level context on what you're trying to do in the top section. "In this notebook we show you how to build a multi-modal retrieval over product reviews. Product reviews inherently have both images and text, and so [explain why product reviews are an interesting multi-modal use case and why we want to ask questions over it]" 
- in general it would be nice to have a bit of text underneath each subsection heading explaining what that section does
- remove commented out lines that aren't used (print statements)

**Comment by jerryjliu** [comment]
- step 7 / 8 aren't actually done in this notebook, i'd remove ("Train a learning to rank model using GPT4V score as label") 
- i wouldn't sell end use case as retraining quite yet, would focus on getting e2e retrieval/reranking working first

- the notebook feels a bit too low-level + the example feels a bit trivial. the entire notebook is focused on executing one query "sandwich". per logan's point, could we package everything into a function and show more interesting queries? this would highlight the utility of this use case more

**Comment by hatianzhang** [comment]
> This looks good to me -- but I almost wonder if the fusion thing should be built into the retriever itself?
> 
> Good education in the meantime 👍🏻

thanks @logan-markewich . For the fusion thing yeah I was planning to refactor into query engine. But it seems put it into retriever side could be a better place.

**Comment by hatianzhang** [comment]
thanks @jerryjliu. sorry for the mispelling and missing some guideline . I probably need to  add a plug-in for mispelling correction  or be more careful next time. But I should mention this version is a draft and just want to get your guys feedback first.

for ```could we package everything into a function and show more interesting queries? this would highlight the utility of this use case more```, yes this is just one example.
If you guys feel it is okay, I will refactor some parts and add more queries

**Pull request closed without merging**
