### PR TITLE
Revert unintended consequence of string node representation update

### PR DESCRIPTION
**Pull request by prrao87**
# Description

Related to the Property Graph Index retriever's `as_retriever` method that allows users to print the string representation of a property graph node or relationship.

I think it makes sense to revert the unintended consequence of string node representation update per #14707, where the [`properties`](https://github.com/run-llama/llama_index/blob/75684082599504e8ae3c31ab580b418a663372b3/llama-index-core/llama_index/core/graph_stores/types.py#L66) dict is coerced to a string and appended to the node name prior to printing the string representation. This caused the string representation of the node to return a garbled mess of `name` + `properties` that make it hard to read when running the following code in the property graph index retriever:

```py
retriever = index.as_retriever(
    include_text=False,  # include source text in returned nodes, default True
)

nodes = retriever.retrieve("What happened at Interleaf and Viaweb?")

for node in nodes:
    print(node.text)
```

The suggested revert to the change made by @logan-markewich now returns the correct results, pretty-printed as follows:

```
Paul Graham -> WORKED_ON -> Viaweb
Viaweb -> PART_OF -> Yahoo
Paul Graham -> WORKED_ON -> Technology companies
Paul Graham -> WORKED_ON -> World Wide Web
```

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested on Kùzu, Neo4j and FalkorDB by rerunning the example notebooks end-to-end, and nothing breaks.

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
@prrao87 I'm pretty sure i made this change because people wanted the node properties in the string representation lol

Instead of removing, there should be a toggle (likely on the retriever)

**Comment by prrao87** [comment]
Interesting the call to `{triplet[n]!s}` per [this line](https://github.com/run-llama/llama_index/blob/044a439dc2fda53c991e49a43e4e8e652dd8a735/llama-index-core/llama_index/core/indices/property_graph/sub_retrievers/base.py#L60) is hardcoded tho, so I'm wondering what a good toggle could be - would it be in the subretriever, or at this upper level in `types.py`?

**Comment by logan-markewich** [comment]
@prrao87 maybe something roughly like

```
.as_retriever(include_properties=True)
```

```
if self.include_properties
  node_text = f"{node} ({node.properties}) -> ..."
else:
  node_text = f"{node} -> ..."
```

**Comment by prrao87** [comment]
> @prrao87 maybe something roughly like
> 
> ```
> .as_retriever(include_properties=True)
> ```
> 
> ```
> if self.include_properties
>   node_text = f"{node} ({node.properties}) -> ..."
> else:
>   node_text = f"{node} -> ..."
> ```

Was exactly trying this but am getting stuck in inheritance hell lol. It applies to the subretriever but I think I need to have the same kwarg in all the retrievers that are being subclassed for the PropertyGraphIndex 😅.

**Comment by logan-markewich** [comment]
@prrao87 yea, there's the base class and 5 other retrievers, not too bad :)

**Comment by prrao87** [comment]
> yea, there's the base class and 5 other retrievers, not too bad :)

Now that you confirmed this, yes, not too bad at all 😅. Fixing now.

**Comment by prrao87** [comment]
Done - I left the default value as `False` because this way, none of the existing example notebooks that call `as_retriever` would need to be rerun. If users want, they can always call the retriever this way:

```py
retriever = index.as_retriever(include_properties=True)
```

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
