### PR TITLE
fix missing dependency error for mongodb docstore

### PR DESCRIPTION
**Pull request by fcakyon**
Related to yesterdays PR: https://github.com/run-llama/llama_index/pull/16632

I missed this in yesterdays PR 🥲 @logan-markewich

### CODE REVIEW

**Review by anoopshrma — APPROVED** [review]
Thanks 👍

**Comment by anoopshrma** [comment]
Could you please check the linting part, build is failing there

**Comment by fcakyon** [comment]
> Could you please check the linting part, build is failing there

fixed now @anoopshrma 💯

**Review by anoopshrma — APPROVED** [review]
Awesome, thanks 👍

**Pull request merged**
