### PR TITLE
Added util functions to get nodes of different depth from a hierarchical nodes list

### PR DESCRIPTION
**Pull request by qiisziilbash**
# Description
Added util functions to get nodes of different depth from a hierarchical nodes list.

When one creates a hierarchical chunking especially with a DB backed vector store, one cannot create an index with nodes of a given chunk easily. This utils enables users to get nodes with different depth which correspond to different chunk sizes and add the chunk size as metadata to the nodes and filter nodes later based on this metadata. 

This can be achieved in a different way as well; which is by adding chunk_size of the `node_parser` to the nodes as metadata when creating the nodes; however, it seems more reasonable to provide utils that enables users to achieve this themselves than making nodes bulkier for every user that might not need this metadata.

## Type of Change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [x] Added new unit/integration tests

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by qiisziilbash** [comment]
> @qiisziilbash if you can fix up the CI errors, we can get this merged
> 
> Seems you may need to update the `__init__.py` or update the import path in the tests
> 
> ```
> ImportError: cannot import name 'get_deeper_nodes' from 'llama_index.node_parser' (/home/runner/work/llama_index/llama_index/llama_index/node_parser/__init__.py)
> ```

Good catch; done!

**Comment by qiisziilbash** [comment]
@logan-markewich feel free to merge this; soes not seem like I have permission to do so

**Comment by logan-markewich** [comment]
@qiisziilbash apologies, with v0.10.0 the project structure has changed slightly. Was focused on getting that landed.

I can take a stab at porting this PR in a bit, if you don't get to it first :)

**Comment by qiisziilbash** [comment]
@logan-markewich this should be good to go in

**Comment by logan-markewich** [comment]
(ugh, merging main locally brought in extra changes, all good though, they will get merged anyways lol)

**Pull request merged**
