### PR TITLE
chore: add o1 models pinned versions

### PR DESCRIPTION
**Pull request by SinghCoder**
# Description

Adding pinned versions of models as per [docs](https://platform.openai.com/docs/models/o1).

## How Has This Been Tested?

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [X] I stared at the code and made sure it makes sense

### CODE REVIEW

**Review by logan-markewich — COMMENTED** [review]
You can bump the version of this integration, so that it publishes on merge

**Comment by SinghCoder** [comment]
> You can bump the version of this integration, so that it publishes on merge

Checking, thanks for really quick reply.

**Comment by SinghCoder** [comment]
> You can bump the version of this integration, so that it publishes on merge

Just a QQ: I don't need to bump this package's version in core or anywhere else right?

**Comment by logan-markewich** [comment]
@SinghCoder nope, you did the right thing 👍🏻

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
