### PR TITLE
fix ollama messages convert when including tool calls info

### PR DESCRIPTION
**Pull request by chrisxiao**
# Description

When the chat messages include tool calls data, it is not added to the message that sent to ollama. so fix it.

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Your pull-request will likely not be merged unless it is covered by some form of impactful unit testing.

- [ ] I added new unit tests to cover this change
- [x] I believe this change is already covered by existing unit tests

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by logan-markewich** [comment]
@chrisxiao tbh, I think this actually makes performance worse 😅 Was testing with `llama3.1:latest` and when including the tool calls in the chat history, it thinks it has to keep using tool calls on each request 🤔 Although not sure if this is just because llama3.1 is dumb, or something else

What's your experience like with this change? What model did you test with?

**Comment by chrisxiao** [comment]
> @chrisxiao tbh, I think this actually makes performance worse 😅 Was testing with `llama3.1:latest` and when including the tool calls in the chat history, it thinks it has to keep using tool calls on each request 🤔 Although not sure if this is just because llama3.1 is dumb, or something else
> 
> What's your experience like with this change? What model did you test with?

Hi @logan-markewich, Thanks for your reply. I am doing some work on learning LLM's function-calling capability. I found this issue because the LLM's response was not as good as I expected when I tested this feature. I don't know if it is accidental or not. I used the Mistral-small model deployed by Ollama. I checked the raw request to Ollama, and found the lack of tools call info. I also checked the Mistral official docs about function-calling and OpenAI's docs about this. I think the tool calls info should be in the history chat messages. 

I put my test env info and referred links below, I hope the information I provided is helpful to you.

My test env:
- Mistral-small model
- Ollama deployed using docker
- Nvidia A10 GPU with 24GB memory

Refs links:
- https://ollama.com/library/mistral-small:latest
- https://docs.mistral.ai/capabilities/function_calling/
- https://openai.com/index/function-calling-and-other-api-updates/

**Comment by logan-markewich** [comment]
@chrisxiao I think they should be too, but tbh I was surprised how much this impacted accuracy when using llama3.1

Did this change improve your accuracy with mistral?

**Comment by chrisxiao** [comment]
> @chrisxiao I think they should be too, but tbh I was surprised how much this impacted accuracy when using llama3.1
> 
> Did this change improve your accuracy with mistral?

In some simple case tests, I didn't notice any change in accuracy, but I'm not sure how it will work in more complex scenarios.

**Comment by chrisxiao** [comment]
> @chrisxiao I think they should be too, but tbh I was surprised how much this impacted accuracy when using llama3.1
> 
> Did this change improve your accuracy with mistral?

In some simple case tests, I didn't notice any change in accuracy, but I'm not sure how it will work in more complex scenarios.

**Comment by chrisxiao** [comment]
> @chrisxiao I think they should be too, but tbh I was surprised how much this impacted accuracy when using llama3.1
> 
> Did this change improve your accuracy with mistral?

In some simple case tests, I didn't notice any change in accuracy, but I'm not sure how it will work in more complex scenarios.

**Pull request merged**
