### PR TITLE
feat(llm): OpenLLM

### PR DESCRIPTION
**Pull request by aarnphm**
Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

cc @parano

# Description

🎉 OpenLLM 🤝 Llama_index

[OpenLLM](https://github.com/bentoml/OpenLLM) is an open-source platform designed to facilitate the deployment and operation of large language models (LLMs) in real-world applications. With OpenLLM, you can run inference on any open-source LLM, deploy them on the cloud or on-premises, and build powerful AI applications.

It includes supports for a wide range of open-source LLMs and model runtimes, including but not limited to Mistral, Llama2, StableLM, Falcon, Dolly, Flan-T5, ChatGLM, and StarCoder.
It also has support for token streaming, quantization, and continuous batching (via vLLM), which can significantly increase the total throughput of LLMs.

With this in mind, this integration to Llama_index brings in two new `LLM`: `OpenLLM` and `OpenLLMAPI`.

For running locally with `OpenLLM`, it will requires user to install `openllm[vllm]` on GPU and `openllm` if running on CPU.

```python
from llama_index.llms.openllm import OpenLLM
llm = OpenLLM('HuggingFaceH4/zephyr-7b-alpha')

llm.complete('I love you')
await llm.acomplete('I love you')

for it in llm.stream_chat(
    [
        ChatMessage(
            role="system", content="You are acting as Ernest Hemmingway."
        ),
        ChatMessage(role="user", content="Hi there!"),
        ChatMessage(role="assistant", content="Yes?"),
        ChatMessage(role="user", content="What is the meaning of life?"),
    ]
):
    print(it.message.content, flush=True, end="")

async for llm.astream_complete("The meaning of life is"): print(it.delta, flush=True, end='')
```

With an OpenLLM server running elsewhere or on [BentoCloud](https://www.bentoml.com/cloud), users will need to install `openllm-client` and use `OpenLLMAPI`:

```python
from llama_index.llms.openllm import OpenLLMAPI

llm = OpenLLM(address='remote.server:3000')
```

> [!NOTE]
> For `OpenLLMAPI`, if `OPENLLM_ENDPOINT` is set, then the following can be achieved:
> ```python
> llm = OpenLLMAPI()
> ```

All async and sync variation of chat and completeion message is supported for both `OpenLLM` and `OpenLLMAPI`.

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by aarnphm** [comment]
Haizz, I do not like mixing async and sync. Stream_chat and stream_complete is partially working right now. I will take another look on this. Maybe it should be openllm responsibility to provide a sync generation.

for `OpenLLM` best for users to use `acomplete`, `astream_complete`, `achat`, `astream_chat` to fully get continuous batching.

**Comment by aarnphm** [comment]
> @aarnphm awesome, thanks for adding this!
> 
> 
> 
> As you know, Open-Source LLMs require a many different input formats depending on the LLM
> 
> 
> 
> Is OpenLLM handling the prompt formating under the hood for each model?

We dont handle and leave the prompt format for the user. For local llm we will rely on apply_chat_templates for chat API.

**Comment by aarnphm** [comment]
`stream_chat` and `stream_complete` is now ready for review.

**Review by logan-markewich — APPROVED** [review]
Assuming CI passes, this looks good to me. Thanks for linking in all the docs

**Comment by logan-markewich** [comment]
Looks like some typing issues around `LLM` -- I would fix it myself right now, but I can't seem to push to this PR

**Comment by aarnphm** [comment]
> Looks like some typing issues around `LLM` -- I would fix it myself right now, but I can't seem to push to this PR

Oh let me fix the type

**Comment by aarnphm** [comment]
cc @logan-markewich

**Comment by logan-markewich** [comment]
Cool! Looks good, thanks for the patience with the CI haha

**Pull request merged**
