### PR TITLE
[version] bump to v0.10.46

### PR DESCRIPTION
**Pull request by nerdai**

### CODE REVIEW

**Review by wadave — APPROVED** [review]
It looks good.

**Review by wadave — APPROVED** [review]

**Comment by nerdai** [comment]
v0.10.46 llama-index core published to PyPi

**Comment by nerdai** [comment]
> v0.10.46 llama-index-core published to PyPi

Thanks for your patience @wadave. As you can see, v0.10.46 of core has been published already. The rest of the CI/CD process will work to publish v0.10.46 of our umbrella package llama-index.

If you don't need to wait for that (e.g. since you use core directly), then by all means. Otherwise, shouldn't be much longer for v0.10.46 for the umbrella llama-index to be published (tagged)

**Comment by wadave** [comment]
@nerdai Thanks for your excellent work.

**Pull request merged**
