### PR TITLE
[Integration] AWS Bedrock Reranker

### PR DESCRIPTION
**Pull request by SuperSecureHuman**
# Description

AWS Bedrock now has rerankers (started with Cohere Reranker 3.5). This PR adds support for it.

https://aws.amazon.com/blogs/machine-learning/cohere-rerank-3-5-is-now-available-in-amazon-bedrock-through-rerank-api/

## Type of Change

- New feature (non-breaking change which adds functionality)

Added Reranker from AWS Bedrock 

## How Has This Been Tested?

Replaced example code from llamaindex to use the AWS Reranker, and made sure it works

### CODE REVIEW

**Comment by SuperSecureHuman** [comment]
Do let me know if anything is needed / modifications are needed

**Comment by SuperSecureHuman** [comment]
image

If this is good to go, I can add a sample notebook

**Comment by brycecf** [comment]
Real unit tests please.  This is not a meaningful test:
```
def test_class():
    names_of_base_classes = [b.__name__ for b in AWSBedrockRerank.__mro__]
    assert BaseNodePostprocessor.__name__ in names_of_base_classes
```

**Comment by logan-markewich** [comment]
I agree with @brycecf -- net new packages should have meaningful tests. You can mock out the api calls to boto3/bedrock for example, or other strategies

**Comment by SuperSecureHuman** [comment]
Hi, I have tried using mock... Please lemme know if anything

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
