### PR TITLE
ClickHouse as a vector store

### PR DESCRIPTION
**Pull request by gingerwizard**
# Description

ClickHouse support as a vector store.

ClickHouse can be used for vector search and is the basis of a number of other technologies such as MyScale. Approximate indices are experimental hence linear scan (fast in ClickHouse) is the default choice.

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by gingerwizard** [comment]
K the whole project struture changed. Working to ensure i adhere to the new format.

**Comment by logan-markewich** [comment]
@gingerwizard yea sorry about that, you just missed it by a day

Vector stores can be added under `llama-index-integrations/vector_stores`

There is a boilerplate script to help generate the initial package. The contributing guide has more details
https://github.com/run-llama/llama_index/blob/main/CONTRIBUTING.md

**Comment by gingerwizard** [comment]
@logan-markewich yeh figured it out, code changes done. Ready for review.

**Comment by gingerwizard** [comment]
@logan-markewich moved to BasePydanticVectorStore

**Comment by gingerwizard** [comment]
@logan-markewich all tests pass, any chance of merging?

**Pull request merged**
