### PR TITLE
Replace redis driver with FalkorDB driver

### PR DESCRIPTION
**Pull request by gkorland**
# Description

Replace redis driver with FalkorDB native python driver

### CODE REVIEW

**Comment by logan-markewich** [comment]
Seems like the new version of falkorDB requires python3.10 -- I'll update the BUILD file for CICD so that tests pass and reflect this requirement

**Comment by logan-markewich** [comment]
Or, I guess I can't push to this PR (must be a private fork)

To fix this
a) In `llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/BUILD` update it to look like this:
```
poetry_requirements(
    name="poetry",
    interpreter_constraints=["==3.10.*"],
)
```

b) In `llama-index-integrations/graph_stores/llama-index-graph-stores-falkordb/pyproject.toml`, bump the version from `0.1.2` to `0.1.3`

**Comment by gkorland** [comment]
We released a new version of the falkordb 1.0.4 client that supports python 3.8

**Review by logan-markewich — APPROVED** [review]

**Comment by gkorland** [comment]
@logan pushed the changes

**Pull request merged**
