### PR TITLE
Update mappings.json

### LINKED ISSUE #11014: [Bug]: Unable to use SelfDiscoverPack
### Bug Description

When I try to use SelfDiscoverPack via download_llama_pack, I'm getting ValueError: Failed to find python package for class SelfDiscoverPack.
How can I use SelfDiscoverPack?

### Version

v0.10.7

### Steps to Reproduce

```
pip install llama_index==0.10.7

import os
os.environ["OPENAI_API_KEY"] = "my-api-key"
from llama_index.llms.openai import OpenAI
llm = OpenAI("gpt-3.5-turbo")

#The code below doesn't work. It gives ValueError: Failed to find python package for class SelfDiscoverPack.
from llama_index.core.llama_pack import download_llama_pack
SelfDiscoverPack = download_llama_pack("SelfDiscoverPack", "./self_discover_pack")
self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)

#The code below doesn't work either. It gives ModuleNotFoundError: No module named 'llama_index.packs'.
#from llama_index.packs.self_discover import SelfDiscoverPack
#self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)
```

### Relevant Logs/Tracbacks

```shell
ValueError                                Traceback (most recent call last)
<ipython-input-5-63247be966cb> in <cell line: 3>()
      1 from llama_index.core.llama_pack import download_llama_pack
      2 
----> 3 SelfDiscoverPack = download_llama_pack("SelfDiscoverPack", "./self_discover_pack")
      4 
      5 self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)

/usr/local/lib/python3.10/dist-packages/llama_index/core/llama_pack/download.py in download_llama_pack(llama_pack_class, download_dir, llama_pack_url, refresh_cache)
     45         new_install_parent = new_import_parent.replace(".", "-").replace("_", "-")
     46     else:
---> 47         raise ValueError(f"Failed to find python package for class {llama_pack_class}")
     48 
     49     if not download_dir:

ValueError: Failed to find python package for class SelfDiscoverPack
```

### PR DESCRIPTION
**Pull request by nerdai**
# Description

- Update mappings.json (need to figure out a better of way doing this in the near future!)

Fixes #11014

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it makes sense

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]

**Comment by logan-markewich** [comment]
Might need to bump and publish a new CLI version too

**Comment by logan-markewich** [comment]
Or wait, does llamaindex-cli read this file in core?

**Comment by nerdai** [comment]
> Or wait, does llamaindex-cli read this file in core?

Oh good catch. No it doesn't. But we need to update the file in cli as well and upgrade the package.

**Comment by nerdai** [comment]
@logan-markewich:

- I updated `mappings.json` for `llama-index-cli`
- I also bumped version in pyproject.toml for `cli` (not `core` in case we didn't want to cut release on that yet)
- I can handle publishing `llama-index-cli` once we're good with the changes.

**Pull request merged**
