### PR TITLE
Ensure backwards compatibility with new Pinecone client version bifucation

### PR DESCRIPTION
**Pull request by aulorbe**
# Description

Pinecone will be releasing a new, major version of its Python client on January 16 (`3.0.0`). The breaking change in this upcoming version is significant -- users using Pinecone version `>=3.0.0.` will be interacting with an entirely new architecture (undergirding the vector DB itself). 

To account for this, third party integrations need to check the `version` of the Pinecone client users are running. If they're running versions `<3.0.0.`, they'll need to instantiate Pinecone indexes via the 'old' method (e.g. `pinecone.init() > pinecone.Index()`; if they're running versions `>=3.0.0.`, they'll be funneled to a new initialization method (e.g. `pinecone.Pinecone() >> pinecone.Index()`. 

This PR encapsulates this `version` bifurcation logic.

This code is checked against the following 3 scenarios. 

❗ Note: internally, we are still on `pinecone-client==3.0.0.dev8`, so this PR should likely wait for merge until `3.0.0.` is officially released and we can test against that.

**1. People using 2.x client:**
    - Unaffected; can connect to indexes made with the 'old' architecture.
    - If these users try to connect to indexes made with the 'new' architecture, they will run into errors.

**2. People using 3.0.0.dev6:**
    - Users trying to connect to indexes made with the 'old' architecture will run into errors.
    - Users trying to connect to indexes made with the 'new' architecture will interact with the new `pinecone.Pinecone()` interface & be able to connect.

**3. People using 3.0.0 (when released):**
    - As long as users are running the newest version of Pinecone (`>=3.0.0`), they will be able to connect to any index, regardless of whether it was made using the 'old' or new architecture.

## Type of Change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end) ➡️ @zackproser will follow up with changes to example notebooks in LlamaIndex repo
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by hatianzhang — COMMENTED** [review]
a lot of our examples are using Pinecone. 
will this new pkg cause any incompatible issues with those existing examples notebook

**Comment by aulorbe** [comment]
> a lot of our examples are using Pinecone. will this new pkg cause any incompatible issues with those existing examples notebook

Yes, it will. As mentioned in the desc for this PR, @zackproser will follow up with a PR (he's already got staged) that makes updates to all example NBs in this repo that use Pinecone 😄

**Comment by hatianzhang** [comment]
nice thanks @aulorbe one side suggestion, could you move some Pinecone util functions into pinecone_util.py to make this main file concise

**Comment by aulorbe** [comment]
> nice thanks @aulorbe one side suggestion, could you move some Pinecone util functions into pinecone_util.py to make this main file concise

Sure thing. Other than that, is it good to ship?

**Comment by aulorbe** [comment]
> nice thanks @aulorbe one side suggestion, could you move some Pinecone util functions into pinecone_util.py to make this main file concise

I can't find any file called `pinecone_utils.py`, but I've made one now in the `utilities` dir.

**Comment by aulorbe** [comment]
Ugh, somehow others' commits got into this git history when I rebased. LMK if you want me to revert and clean up the history. Otherwise, I can just squash upon merge.

**Comment by hatianzhang** [comment]
@aulorbe pls git merge those changes to make it clean. so that we could easily review your own changes
thanks

**Comment by hatianzhang** [comment]
> > nice thanks @aulorbe one side suggestion, could you move some Pinecone util functions into pinecone_util.py to make this main file concise
> 
> I can't find any file called `pinecone_utils.py`, but I've made one now in the `utilities` dir.

oh you can create a new file for `pinecone_utils.py`

**Comment by aulorbe** [comment]
> @aulorbe pls git merge those changes to make it clean. so that we could easily review your own changes thanks

Done! But looks like I need approval from you for some workflow stuff now.

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
