### PR TITLE
Added a bedrock example

### PR DESCRIPTION
**Pull request by hustshawn**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ x ] Added new notebook (that tests end-to-end)
- [ x ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by hatianzhang** [comment]
@hustshawn thanks for the example.
We already have one for bedrock https://github.com/run-llama/llama_index/blob/main/docs/examples/llm/bedrock.ipynb

Can you tell us what is the main difference between yours and that one

**Comment by hustshawn** [comment]
> @hustshawn thanks for the example. We already have one for bedrock https://github.com/run-llama/llama_index/blob/main/docs/examples/llm/bedrock.ipynb
> 
> Can you tell us what is the main difference between yours and that one

Ok, I didn't realize there is one. But still, it's good to put the example in a separate folder which can be easier to find.

**Comment by hatianzhang** [comment]
@hustshawn this https://github.com/run-llama/llama_index/tree/main/examples folder will be deprecated in the future.
Please move your example to https://github.com/run-llama/llama_index/tree/main/docs/examples/llm
If it is already very similar to https://github.com/run-llama/llama_index/blob/main/docs/examples/llm/bedrock.ipynb, you can append something new into the existing `Bedrock` notebook

**Comment by hatianzhang** [comment]
@hustshawn looks most of examples in your example is the same as existing https://github.com/run-llama/llama_index/blob/main/docs/examples/llm/bedrock.ipynb.
To avoid dups, going to close this pr.
Let me know if I am wrong
thanks

**Pull request closed without merging**
