### PR TITLE
Remove circular package dep

### PR DESCRIPTION
**Pull request by logan-markewich**
OpenAI LLM depends on OpenAI Agent which depends on OpenAI LLM which.... yea

While this doesn't break pip per say, other systems in the python ecosystem may not like this

Instead, factored out the common code into a new openai utils package

### CODE REVIEW

**Comment by masci** [comment]
Can't we just move `resolve_tool_choice` into the LLM package and remove its dependency from the Agent package?

**Comment by logan-markewich** [comment]
ah ya, that makes more sense

**Review by tbeamish-benchsci — APPROVED** [review]
Looks great. Thanks!

**Comment by logan-markewich** [comment]
(box tests failing are ok, they are aware)

**Pull request merged**
