### PR TITLE
Google Vertex Support 

### PR DESCRIPTION
**Pull request by yureikami**
# Description

I've created this pull request to introduce the Google Vertex Client to the Llama Index ecosystem since it currently only supports the Palm API, so this PR is aimed at enabling the integration of the Vertex Client.

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by hatianzhang** [comment]
@yureikami there are some lint errors. could you help fix those errors first
thanks a lot of your contribution

**Comment by yureikami** [comment]
Fixed most of the linting errors

**Comment by hatianzhang** [comment]
thanks a lot
looks there are still some lint issues.
Pls follow other LLM prs like https://github.com/run-llama/llama_index/pull/8223 
adding Vertex into `llama_index/llms/loading.py and docs/core_modules/model_modules/llms/modules.md`. Pls also add your change into CHANGELOG.md file

**Review by Disiok — APPROVED** [review]
Amazing, thanks so much for the contribution!

**Pull request merged**
