### PR TITLE
[chore]: delete llama-index-legacy

### PR DESCRIPTION
**Pull request by logan-markewich**
The package is still published and available, but this doesn't need to be in our codebase anymore

### CODE REVIEW

**Review by masci — APPROVED** [review]
🔥

**Comment by Digma** [comment]
@logan-markewich Is there any reason it is still mention in https://github.com/run-llama/llama_index/blob/main/pyproject.toml#L52C1-L52C31 ? 

In our case, llama-index-legacy depends on tenacity<0.9.0 which is causing some issues with other dependencies we have. We were wondering if there is any reason to still have `llama-index-legacy` as a dependency in `llama-index-core`?

**Comment by masci** [comment]
@Digma that's most likely a leftover, would you have time to open a PR to remove it from there?

**Comment by Digma** [comment]
Sure, will do it today

**Pull request merged**
