### PR TITLE
integrate openai function calling 

### PR DESCRIPTION
**Pull request by jerryjliu**
migrate OpenAI LLM to use function calling LLM abstraction, letting us remove the old code 
- added predict_and_call examples to OpenAI notebook 
- also fixed up the openai notebook, it was using davinci

### CODE REVIEW

**Review by nerdai — APPROVED** [review]
lgtm.

I think all of the changes are under the hood, and don't affect our users, so we don't need to concern ourselves with any backwards compat issues?

**Comment by nerdai** [comment]
🤔`resume-screener-pack-test` is failing?

**Comment by nerdai** [comment]
> 🤔`resume-screener-pack-test` is failing?

ohh, i think we might need to update the `llama-index-llms-openai` dependency for all packs/integrations that depend on it after landing this update. Pants might fail a bunch of these actually.

```
llama-index-packs/llama-index-packs-resume-screener/llama_index/packs/resume_screener/__init__.py:1: in <module>
    from llama_index.packs.resume_screener.base import ResumeScreenerPack
llama-index-packs/llama-index-packs-resume-screener/llama_index/packs/resume_screener/base.py:8: in <module>
    from llama_index.llms.openai import OpenAI
llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/__init__.py:1: in <module>
    from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py:18: in <module>
    from llama_index.core.llms.function_calling import FunctionCallingLLM
E   ModuleNotFoundError: No module named 'llama_index.core.llms.function_calling'
```

**Comment by logan-markewich** [comment]
I can fix the pants 👍🏻

**Comment by logan-markewich** [comment]
I think I'll have to merge this after releasing core, will make a release today

**Pull request merged**
