### PR TITLE
Cassandra vector-store notebook updates

### PR DESCRIPTION
**Pull request by hemidactylus**
As a twin PR to #8777 (now merged), this PR adapts the dependencies and naming scheme for better clarity over which connectors covers which kind of database/protocol. Additionally, URLs are updated to point to the latest quickstart and landing pages (both Astra and Cassandra), and more details are provided for the case of connecting to a Cassandra cluster.

Thank you!

### CODE REVIEW

**Comment by logan-markewich** [comment]
I noticed all the notebook outputs got erased -- do you mind running that again?

**Comment by hatianzhang** [comment]
pls output the response otherwise LGTM!

**Comment by hemidactylus** [comment]
Ah, right, sorry and thank you for noticing! - let me re-run and update the PR momentarily

**Comment by hemidactylus** [comment]
@hatianzhang Apologies, it's all back in now :)
Thank you!

**Pull request merged**
