### PR TITLE
Box refactor: Box File to Llama-Index Document adaptor

### PR DESCRIPTION
**Pull request by barduinor**
# Description

Created an adaptor to map the extensive Box File object to the Llama-Index Document Matadata

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.
- [x] Refactor/Improvement 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by nerdai — COMMENTED** [review]
Thanks @barduinor. Looks good to me -- it seems like a bit of a refactor of the `box_api.py` methods. These methods seem to be util funcs that a llama-index user wouldn't necessarily use. Is that correct?

Just wondering if we need to be concerned about breaking changes here?

**Comment by nerdai** [comment]
Also @barduinor can you kindly bump the version number in this integration's `pyproject.toml`?

**Comment by barduinor** [comment]
Hi @nerdai 

That is correct, no breaking changes. The code was a bit sloppy, and I wanted to have a clear separation between Box objects and Llama-Index objects. That led me to create an adaptor to translate between the Box File object and the Llama-Index Document, and use it consistently in the readers and tools.

From a 3rd party developer perspective the readers and tools method signatures remain the same.

Cheers

**Comment by nerdai** [comment]
Perfect, thanks @barduinor for the confirmation! Nice work :)

**Comment by barduinor** [comment]
Thank you @nerdai , much appreciated.

**Pull request merged**
