### PR TITLE
Fix AsyncOpenAI "RuntimeError: Event loop is closed bug" when instances of AsyncOpenAI are rapidly created & destroyed

### PR DESCRIPTION
**Pull request by philipchung**
… avoid https://github.com/openai/openai-python/pull/1262

# Description

When `AsyncOpenAI` classes are rapidly created and destroyed, the underlying `httpx.AsyncClient` is not properly opened and closed unless requests are made from a context manager.  `AsyncOpenAI` clients underlie LlamaIndex `OpenAI` and `OpenAI-Like` classes, so if we rapidly create and destroy these (e.g. in multithread/multiprocess context) this error will arise. This PR just wraps the `completions.create()` calls within a client context manager and ensures that the underlying `httpx.AsyncClient` used by the OpenAI python client is properly opened and closed.

For completeness, `completion.create()` requests from the Sync OpenAI client are also wrapped in a client context manager. This PR also aligns the `_achat()` method to return logprobs similar to `_chat()` method.

Fixes issues raised in https://github.com/openai/openai-python/pull/1262, https://github.com/openai/openai-python/issues/1254

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense
- [x] I implemented it in my project code and it resolves the RuntimeError 

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
@philipchung This seems to have caused more issues when I run your branch?

```python
from llama_index.llms.openai import OpenAI
from llama_index.core.llms import ChatMessage

llm = OpenAI()

async def arun():
  await llm.acomplete("Hello World!")
  gen = await llm.astream_complete("Hello world!")
  async for token in gen:
    pass
  await llm.achat([ChatMessage(role="user", content="Hello World!")])
  gen = await llm.astream_chat([ChatMessage(role="user", content="Hello World!")])
  async for token in gen:
    pass

def run():
  llm.complete("Hello World!")
  gen = llm.stream_complete("Hello world!")
  for token in gen:
    pass
  llm.chat([ChatMessage(role="user", content="Hello World!")])
  gen = llm.stream_chat([ChatMessage(role="user", content="Hello World!")])
  for token in gen:
    pass


async def run_many():
  tasks = [arun(), arun(), arun()]
  await asyncio.gather(*tasks)

# test async
import asyncio
tasks = [arun(), arun(), arun()]
asyncio.run(run_many())

# test sync
run()
```

I get this error

```
RuntimeError: Cannot send a request, as the client has been closed.
```

If I install an older version of the openai package, it works fine though

**Comment by logan-markewich** [comment]
I know using a global LLM is probably not advisable, but I know many users who do this

**Comment by philipchung** [comment]
I believe I resolved the issues, and running your test code works.  Also passes pytest. 

Changes are:
1. Using a client context manager closes the connection pool after leaving the context block, so if reuse_client=True, then this would cause an error for future completion.Create() calls. I changed the code to only use only client context manager if reuse_client=False.
2. I removed client context manager from streaming methods so they are now unchanged. It was unclear to me how to implement the client context manager with a generator.  Also, use cases with streaming completion.Create() calls are unlikely to use multithread/multiprocessing.

**Comment by logan-markewich** [comment]
Yea streaming is kind of hard in this case -- lgtm otherwise now

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
