### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by anoopshrma**
# Description

Updating readme for the integrations which contain empty readme

### CODE REVIEW

**Comment by logan-markewich** [comment]
Hey @anoopshrma -- should we merge what you have so far? Or are you still picking away at this?

**Comment by anoopshrma** [comment]
> Hey @anoopshrma -- should we merge what you have so far? Or are you still picking away at this?

Hey, I'm picking at this. Just got busy with deployment at my company that's why wasn't able to add anymore to it. 
Will add more to it and will let you know

**Comment by logan-markewich** [comment]
No worries! Was just going through all the PRs and thought I'd check in, makes sense 👍

**Comment by anoopshrma** [comment]
Hey @logan-markewich , I have updated readers readme. 
Will start working on LLM integration readme 🚀 in my next PR

**Comment by logan-markewich** [comment]
We can probably merge this for now, thanks a ton @anoopshrma ❤️

**Review by logan-markewich — APPROVED** [review]

**Comment by nerdai** [comment]
@anoopshrma for the win!!!! 🌟😤🏆

**Comment by anoopshrma** [comment]
Thanks @logan-markewich , @nerdai 
 I'll pick another section this weekend! 

PS: I accidently tapped on disabling auto squash that Logan had enabled! 🙏

**Pull request merged**
