### PR TITLE
fix the bug on vector_search_profile "default"(this profile did not exist)  and add the possibility to choose language_analyzer of searchable fields

### LINKED ISSUE #10522: [Bug]: Azure AI search UnkownVectorAlgorithmConfiguration
### Bug Description

Azure Ai search llama index set up embedding_field_key error.
Screenshot 2024-02-08 210159
image

https://docs.llamaindex.ai/en/stable/examples/vector_stores/AzureAISearchIndexDemo.html

followed this link to setup but issue persisted.

### Version

(0.9.45.post1)

### Steps to Reproduce

NIL

### Relevant Logs/Tracbacks

_No response_

### PR DESCRIPTION
**Pull request by ryanrib14**
# Description
I changed the selection of the vector_search_profile that was previously set as "default" behind the scenes but this profile did not exist in the defaults that were defined causing an error when creating the index, so I added the possibility for the user to choose between the two available profiles' myHnsw' and 'myExhaustiveKnn'. Furthermore, as I am a Brazilian developer I was facing performance problems with the default language analyzer in searchable fields which was defined as "en.lucene" so I added the possibility for the user to choose which one is best for their case and documents language.
the list of analyzers:https://learn.microsoft.com/en-us/azure/search/index-add-language-analyzers

I also suggest that in a next PR add the possibility of choosing the similarity metric.

Fixes #10522

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I ran the existing notebook testing the modifications "AzureAISearchIndexDemo.ipynb"
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by hatianzhang — APPROVED** [review]
LGTM !

**Comment by logan-markewich** [comment]
@ryanrib14  apologies, with v0.10.0 the project structure has changed slightly

I can take a stab at porting this PR in a bit, if you don't get to it first :)

**Comment by ryanrib14** [comment]
> @ryanrib14 apologies, with v0.10.0 the project structure has changed slightly
> 
> I can take a stab at porting this PR in a bit, if you don't get to it first :)

i can take is now if you don't yet

**Comment by ryanrib14** [comment]
> @ryanrib14 pls go ahead! thanks

https://github.com/run-llama/llama_index/pull/10675

**Pull request closed without merging**
