### PR TITLE
Initialize MultiModal Retrieval using LlamaIndex

### PR DESCRIPTION
**Pull request by hatianzhang**
# Description

Multi-Modal Retrieval for text and images
Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
thanks @hatianzhang ! This looks great, and I agree with Simon. Would be interesting to explore complex documents like product reviews. Maybe we can actually try hierarchical/recursive retrieval to 1) retrieve docs first, then 2) within doc retrieve both text and images to feed into LLaVa. 

anyone i'm good to land this whenever nits are cleaned up, can publish tomorrow

**Comment by hatianzhang** [comment]
thanks @Disiok and @jerryjliu I will do a polish tmrw and get it done.
Also briefly synced with @Disiok for some high level design for MM abstract class so that we can onboard MM model more easily for any downstream tasks

**Comment by ravi03071991** [comment]
@hatianzhang Would be good if you can add google colab support for the notebook.

**Comment by hatianzhang** [comment]
@ravi03071991 any suggestion how to do this easily?

**Review by Disiok — APPROVED** [review]

**Pull request merged**
