### PR TITLE
Add ``fail_on_http_error`` arg to github repository reader.

### LINKED ISSUE #12649: [Feature Request]: Add `fail_on_http_error` boolean to Github readers
### Feature Description

We are getting an error when trying to pull files from the github api using the `GithubRepositoryReader`. 

So far we have added a timeout and retries argument to the reader to try resolve this but it still seems to fail and so instead we have added a try/except in our own code to catch the HTTPError and then just continue onto the next repo we are trying to get data from. This means that if one request fails when getting data from the repo then we skip the whole repo. 

We would like to add a `fail_on_http_error` flag to the readers which would allow us to have an if statement which catches the exception and continue onto the next file if `False` or keep the current behaviour of raising an exception if `True`.

### Reason

Continue onto next file if there is a error when requesting a file from the Github API.

### Value of Feature

Rather than skipping the whole repo if one request fails we could just skip that file. This would allow us to get more complete data.

### PR DESCRIPTION
**Pull request by rwood-97**
# Description

This adds a `fail_on_http_error` argument to the GithubClient in the GithubRepositoryReader.
When running `get_blob`, if `fail_on_http_error` is set to `True` a  HTTPError will be raised or, if set to `False`, None will be returned and blob is skipped.

Fixes #12649 

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests **NEEDS REVIEW**
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works **NEEDS REVIEW**
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by nerdai** [comment]
Hey @rwood-97, would you be able to run `pants tailor ::` if you have `pants` installed?

**Comment by nerdai** [comment]
> Tests are failing since there is a problem with some imports, not sure how to fix this as they do work on my laptop but are flagged by ruff as unresolvable.

Yeah sorry @rwood-97... it looks like an issue with `llama-index-readers-file` dep and our pants configuration. We've seen this a few times before — just tried applying a fix for it.

**Review by nerdai — APPROVED** [review]
thanks @rwood-97 for the contribution!

**Comment by rwood-97** [comment]
It might be you could just put an empty string as github token and the tests should work since I'm mocking all the API requests, will do this in a separate PR and test.

**Pull request merged**
