### PR TITLE
Add Multimodal Video RAG example 

### PR DESCRIPTION
**Pull request by raghavdixit99**
# Description

Have added a better-suited example for LanceDB - llama integration , Removed redundant old examples. Updated integration doc.

## Type of Change
Example updation
- [ ] This change requires a documentation update

# How Has This Been Tested?
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by hatianzhang — APPROVED** [review]
LGTM! awesome combination of video, audio, image, text

**Comment by jerryjliu** [comment]
awesome example!

**Comment by raghavdixit99** [comment]
@hatianzhang , @jerryjliu , this commit has deleted many files including our example from the main repo -  https://github.com/run-llama/llama_index/commit/369973f4e8c1d6928149f0904b25473faeadb116

This breaks any tweets or blog posts that we are gonna release soon as the link is not found , can you please fix this ?

**Comment by hatianzhang** [comment]
@raghavdixit99 we are pushing 0.10.0 which is a big refactoring.
sorry for the change and it seems your file got deleted. we will bring it back asap

**Comment by hatianzhang** [comment]
@raghavdixit99 I bring back your example in https://github.com/run-llama/llama_index/pull/10598

could you help do a check and make sure it works as expected

**Comment by raghavdixit99** [comment]
@hatianzhang everything runs fine , but we need to install whisper as well , could you please just commit the following line - 

%pip install -U openai-whisper

or should I raise a PR for this?

**Comment by hatianzhang** [comment]
@raghavdixit99 pls go ahead and make a pr for us

**Pull request merged**
