### PR TITLE
Fix typo in property name

### PR DESCRIPTION
**Pull request by mrkn**
Fixes the following error introducing by yesterday's commit 718e1f5a12b926059d76f6dfbbcbb21b0079ac80:

```
AttributeError: 'OpensearchVectorClient' object has no attribute 'os_version'
Python stacktrace:
 [1] _is_efficient_filtering_enabled
   @ llama_index.vector_stores.opensearch.base ~/.cache/pypoetry/virtualenvs/rag-company-rules-q2Dy5nHQ-py3.11/lib/python3.11/site-packages/llama_index/vector_stores/opensearch/base.py:637
 [2] __init__
   @ llama_index.vector_stores.opensearch.base ~/.cache/pypoetry/virtualenvs/rag-company-rules-q2Dy5nHQ-py3.11/lib/python3.11/site-packages/llama_index/vector_stores/opensearch/base.py:126
```

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Your pull-request will likely not be merged unless it is covered by some form of impactful unit testing.

- [ ] I added new unit tests to cover this change
- [ ] I believe this change is already covered by existing unit tests

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by mrkn** [comment]
@Aydin-ab Could you please have a look this?

**Review by nerdai — COMMENTED** [review]
Can you bump version as well.

**Comment by mrkn** [comment]
@nerdai The version was bumped.

**Review by nerdai — APPROVED** [review]
LGTM thanks!

**Comment by nerdai** [comment]
Thanks for the fix. Going to ignore Coverall's check for this integration for now.

**Pull request merged**
