### PR TITLE
Feature (#8039): change fixed default variables as function parameters.

### PR DESCRIPTION
**Pull request by aaronjimv**
# Feature (#8039): Add min_seconds and max_seconds as a parameter to the _create_retry_decorator function (#8039)

# Description

This PR includes the changes requested in [Feature Request]: Configurable retry time for LLM calls #8039
I changed the min_seconds and max_seconds variables as parameters of the function def _create_retry_decorator().
User can now to configure these values.

Fixes # (8039)

## Type of Change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by aaronjimv** [comment]
Hello, I am new to open source collaboration and I am open to any feedback or suggestion

**Comment by nerdai** [comment]
> Hello, I am new to open source collaboration and I am open to any feedback or suggestion

Welcome! Happy to have you here!

**Review by nerdai — CHANGES_REQUESTED** [review]
Looks good @aaronjimv! Though, you have some conflicts with current branch. Can you resolve them and push up the changes?

**Comment by aaronjimv** [comment]
Yes. I will doing.

**Comment by aaronjimv** [comment]
Hi @nerdai. Please, let me know if I need to change anything else.
Thank you.

**Review by nerdai — APPROVED** [review]
LGTM!

**Comment by aaronjimv** [comment]
Thank you, I appreciate it.

**Pull request merged**
