### PR TITLE
[version] vbump to v0.10.45post1

### PR DESCRIPTION
**Pull request by nerdai**

### CODE REVIEW

**Review by wadave — APPROVED** [review]
Thanks. it looks good.

**Comment by wadave** [comment]
Hi Andrei,
Does llama-index-core version need to be bumped again, rebuilt and published too?
I clone the repo to local, install locally, it works. 
However, when installing using pypi, it still cannot pick up the latest files from 
https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/utilities/gemini_utils.py

TL;DR
MessageRole.TOOL has been added to the file. it still shows the error below:

~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:37, in merge_neighboring_same_role_messages(messages)
     [32](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:32) merged_content = [current_message.content]
     [34](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:34) # Check if the next message exists and has the same role
     [35](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:35) while (
     [36](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:36)     i + 1 < len(messages)
---> [37](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:37)     and ROLES_TO_GEMINI[messages[i + 1].role]
     [38](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:38)     == ROLES_TO_GEMINI[current_message.role]
     [39](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:39) ):
     [40](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:40)     i += 1
     [41](https://vscode-remote+ssh-002dremote-002bwangdave-002ec-002egooglers-002ecom.vscode-resource.vscode-cdn.net/usr/local/google/home/wangdave/projects/agentic_rag/~/miniconda3/lib/python3.11/site-packages/llama_index/core/utilities/gemini_utils.py:41)     next_message = messages[i]

KeyError: <MessageRole.TOOL: 'tool'>

**Comment by nerdai** [comment]
Oh strange. I just tried on a fresh virtualenv using pyenv and it seems to have install v0.10.45 of llama-index-core:

```
pyenv virtualenv llama-test
pyenv activate llama-test
pip install llama-index
```

Checking what versions of packages installed:
```sh
pip freeze | grep llama-index
```

```
llama-index==0.10.45.post1
llama-index-agent-openai==0.2.7
llama-index-cli==0.1.12
llama-index-core==0.10.45
llama-index-embeddings-openai==0.1.10
llama-index-indices-managed-llama-cloud==0.1.6
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.22
llama-index-multi-modal-llms-openai==0.1.6
llama-index-program-openai==0.1.6
llama-index-question-gen-openai==0.1.3
llama-index-readers-file==0.1.25
llama-index-readers-llama-parse==0.1.4
```

**Comment by wadave** [comment]
/llama-index-core/pyproject.toml needs to be bumped and rebuilt. I guess

**Comment by nerdai** [comment]
Can you run `pip freeze | grep llama-index` while your virtualenv is active? For me, it did install `v0.10.45` of llama-index-core which is what we want right?

**Comment by wadave** [comment]
```
llama-index==0.10.45.post1
llama-index-agent-openai==0.2.7
llama-index-cli==0.1.12
llama-index-core==0.10.45
llama-index-embeddings-openai==0.1.10
llama-index-embeddings-vertex==0.1.0
llama-index-indices-managed-llama-cloud==0.1.6
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.22
llama-index-llms-vertex==0.2.0
llama-index-multi-modal-llms-openai==0.1.6
llama-index-program-openai==0.1.6
llama-index-question-gen-openai==0.1.3
llama-index-readers-file==0.1.25
llama-index-readers-llama-parse==0.1.4
llama-index-vector-stores-vertexaivectorsearch==0.0.1
```

It shows 10.45 for llama-index-core, but it does not include the latest python files. 

https://pypi.org/project/llama-index-core/ is not updated!

I guess when the version was miss-matched on June 14, 10.45 for llama-index-core build picked up 10.44 version of files. 
Could you rebuild 10.45 for llama-index-core? or have to bump this version to be published to pypi

**Comment by wadave** [comment]
```
llama-index==0.10.45.post1
llama-index-agent-openai==0.2.7
llama-index-cli==0.1.12
llama-index-core==0.10.45
llama-index-embeddings-openai==0.1.10
llama-index-embeddings-vertex==0.1.0
llama-index-indices-managed-llama-cloud==0.1.6
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.22
llama-index-llms-vertex==0.2.0
llama-index-multi-modal-llms-openai==0.1.6
llama-index-program-openai==0.1.6
llama-index-question-gen-openai==0.1.3
llama-index-readers-file==0.1.25
llama-index-readers-llama-parse==0.1.4
llama-index-vector-stores-vertexaivectorsearch==0.0.1
```
https://pypi.org/project/llama-index-core/ is  not updated.

On June 14, when the version miss-match, llama-index-core seems to install the old files (44 version). I guess.

**Comment by wadave** [comment]
I download and check the https://pypi.org/project/llama-index-core file.
It does include the OLD files, not the latest from https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/utilities/gemini_utils.py

**Comment by nerdai** [comment]
Ah okay, sorry for the confusion here but it seems we've conflated two things:

1. The version dependency misalignment of llama-index-core in the "umbrella" package of llama-index

2. The need for a new version of `llama-index-core` to be released

Fixing 1. does not fix your need with 2. That is because, the changes to `llama-index-core/llama_index/core/utilities/gemini_utils.py` came after I published v0.10.45 of llama-index-core (see image below).

image

**Comment by nerdai** [comment]
I'm just going to cut a new release of llama-index-core and llama-index v0.10.46 very soon. Just waiting for another PR that my colleague is working on so that its also included in this latest release.

**Comment by nerdai** [comment]
(Or maybe it was just me conflating things here and misunderstanding you to begin with!)

**Comment by wadave** [comment]
awesome! thanks for the explanation. I think your solution will work.

**Pull request merged**
