### PR TITLE
Fix the ElasticsearchStore key error

### PR DESCRIPTION
**Pull request by davialvb**
Change None to empty dict and add get metadata using function get to avoid key error.

# Description

When there is no metadata in the Elasticsearch index, a `KeyError: 'metadata'` occurs during retrieval. If you try to use the `get` function to avoid this key error, a new error arises from Pydantic. `ValidationError: 1 validation error for TextNode`

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by nerdai — COMMENTED** [review]
Thanks @davialvb! Would you mind sharing more of the traceback for the Pydantic Validation error?

Also can you please bump the version number if the integrations pyproject.toml?

**Comment by davialvb** [comment]
The error is just because is expected a dict by TextNode, and not a None.
I changed None to empty dict, it solves the problem. 

traceback:
```
ValidationError: 1 validation error for TextNode
metadata
  Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/dict_type
```

**Comment by nerdai** [comment]
> The error is just because is expected a dict by TextNode, and not a None. I changed None to empty dict, it solves the problem.
> 
> traceback:
> 
> ```
> ValidationError: 1 validation error for TextNode
> metadata
>   Input should be a valid dictionary [type=dict_type, input_value=None, input_type=NoneType]
>     For further information visit https://errors.pydantic.dev/2.8/v/dict_type
> ```

Got it, thanks! Just wanting to confirm if there was anything needed to be done on `TextNode` class itself. Your solution is the right one.

**Review by nerdai — APPROVED** [review]
LGTM!

**Comment by Yin-1** [comment]
I had the same question.

**Pull request merged**
