### PR TITLE
IndexedMongoDBKVStore

### PR DESCRIPTION
**Pull request by sourabhdesai**
# Description

Adding an `IndexedMongoDBKVStore` variant which allows for queryability over other attributes set on the MongoDB objects other than the `key` *(i.e. `id_`)*.

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by hatianzhang — APPROVED** [review]
lgtm

**Comment by logan-markewich** [comment]
@sourabhdesai do we still need this?

**Comment by sourabhdesai** [comment]
> @sourabhdesai do we still need this?

@logan-markewich yes but def not urgent

**Comment by logan-markewich** [comment]
I will have to merge in v0.10.0 for this change in a bit

**Comment by logan-markewich** [comment]
Going to close this one out for now, its quite outdated at this point

If its still an issue, please raise an updated PR

Sorry for letting this one sit for so long!

**Pull request closed without merging**
