### PR TITLE
bug fixed in OpenInference log that cause error with importing

### PR DESCRIPTION
**Pull request by azurewtl**
# Description

when import OpenInference log using `query_ds = Dataset.from_open_inference(query_df)`, an error will raise because a column name is not matched by following REGEX:
> file_path = `phoenix/datasets/dataset.py`
``` python
def _parse_open_inference_column_name(column_name: str) -> _OpenInferenceColumnName:
    pattern = (
        r"^:(?P<category>\w+)\.(?P<data_type>\[\w+\]|\w+)(\.(?P<specifier>\w+))?:(?P<name>.*)?$"
    )
    ...
   ...
    raise ValueError(f"Invalid format for column name: {column_name}")
```

Obviously it's just a simple TYPO, other column name following naming convention
> file_path = `llama_index/callbacks/openinference/base.py`
``` python
@dataclass
class QueryData:
    """
    Query data with column names following the OpenInference specification.
    """
    node_ids: List[str] = field(
        default_factory=list,
        metadata={
            OPENINFERENCE_COLUMN_NAME: ":feature.[str].retrieved_document_ids:prompt"
        },
    )
    scores: List[float] = field(
        default_factory=list,
        metadata={
            OPENINFERENCE_COLUMN_NAME: (
                ":feature.[float].retrieved_document_scores:prompt"
            )
        },
    ...
    ...
```

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by logan-markewich** [comment]
Do you mind bumping the version in the pyproject.toml file for the package on this vector store?

**Comment by azurewtl** [comment]
> Do you mind bumping the version in the pyproject.toml file for the package on this vector store?

I don't get what to do. I need to bump what version in pyproject.toml file?
```python
[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
llama-index-legacy = "^0.9.48"
llama-index-llms-openai = "^0.1.5"
llama-index-embeddings-openai = "^0.1.5"
llama-index-program-openai = "^0.1.3"
llama-index-question-gen-openai = "^0.1.2"
llama-index-agent-openai = "^0.1.4"
llama-index-readers-file = "^0.1.4"
llama-index-readers-llama-parse = "^0.1.2"
llama-index-indices-managed-llama-cloud = "^0.1.2"
llama-index-core = "^0.10.16"
llama-index-multi-modal-llms-openai = "^0.1.3"
llama-index-cli = "^0.1.2"
```

**Comment by logan-markewich** [comment]
The version of the opensearch package itself... one sec I can do it too

**Review by logan-markewich — APPROVED** [review]

**Comment by azurewtl** [comment]
> The version of the opensearch package itself... one sec I can do it too

Thanks, I just didn't get what to do. How does changing "[" brackets effect opensearch version

**Pull request merged**
