### PR TITLE
Add Astra DB batched insertion for large multi-doc inserts

### PR DESCRIPTION
**Pull request by erichare**
# Description

This update supports the latest Astra DB API interface, and ensures that bulk document insertions above the Astra-defined limit proceed in a batched fashion. It also cleans up a few components of the Astra DB example notebook accordingly.

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it makes sense

(Note that an existing test and notebook already exist and are updated accordingly)

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by erichare** [comment]
@nerdai If you get a chance to take a peek at this, this is a small update mostly to address something that's on our backend - minor changes overall, but addressing a fairly important issue (a current batch size limitation for inserts on our side). Thanks again for all the reviews you've done already :) Really appreciate it.

**Review by nerdai — APPROVED** [review]
LGTM! Thanks @erichare 🙏

**Comment by nerdai** [comment]
Do you mind making a quick entry in CHANGELOG?

**Comment by erichare** [comment]
@nerdai Just added an entry in the changelog! Thank you!

**Pull request merged**
