### PR TITLE
Cleanlab's cookbook

### PR DESCRIPTION
**Pull request by AshishSardana**
# Description

A new cookbook to showcase how to utilize Cleanlab Trustworthy Language Model's (TLM)`trustworthiness_score` in a RAG pipeline.

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Review by logan-markewich — APPROVED** [review]
Cool demo!

If I could suggest one change, it would make the notebook more realistic if we attached some metadata to the events

For example, we recently added this API that would be fun to show off
```python
from llama_index.core.instrumentation.dispatcher import instrument_tags

with instrument_tags({"user_id": "1234"):
  response = query_engine.query(...)
```
Then, each `event.tags` will have the tags above, letting users sort/filter/etc :)

**Comment by logan-markewich** [comment]
I actually would be very surprised if the latest broke something 👀 unless you wrote this with v0.9.x 😅

**Comment by logan-markewich** [comment]
Ok, well I'll merge this now, but I encourage an update to use that new tagging api :)

**Comment by AshishSardana** [comment]
I'm on 0.10.45. I'll update to latest and share my observations while I update it to use the new API :)

**Pull request merged**
