### PR TITLE
fix: update `OpenAIAssistantAgent` to use `attachments` rather than `file_ids`

### LINKED ISSUE #12968: [Bug]: OpenAIAssistantAgent now breaks because of OpenAI api changes
### Bug Description

OpenAI changed their api and now llama-index has errors with OpenAIAssistantAgent.

[Comment](https://community.openai.com/t/typeerror-messages-create-got-an-unexpected-keyword-argument-file-ids/722104) from OpenAI about the issue I believe.
From  [https://docs.llamaindex.ai/en/stable/examples/agent/openai_assistant_agent/](LLama Index example code)
```python
from llama_index.agent.openai import OpenAIAssistantAgent

agent = OpenAIAssistantAgent.from_new(
    name="Math Tutor",
    instructions="You are a personal math tutor. Write and run code to answer math questions.",
    openai_tools=[{"type": "code_interpreter"}],
    instructions_prefix="Please address the user as Jane Doe. The user has a premium account.",
)
```

How should I resolve this until it gets resolved in a better manner?

### Version

0.10.30

### Steps to Reproduce

```python
from llama_index.agent.openai import OpenAIAssistantAgent

agent = OpenAIAssistantAgent.from_new(
    name="Math Tutor",
    instructions="You are a personal math tutor. Write and run code to answer math questions.",
    openai_tools=[{"type": "code_interpreter"}],
    instructions_prefix="Please address the user as Jane Doe. The user has a premium account.",
)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File ".../projects/server/error.py", line 7, in <module>
    agent = OpenAIAssistantAgent.from_new(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/llama_index/agent/openai/openai_assistant_agent.py", line 230, in from_new
    assistant = client.beta.assistants.create(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Assistants.create() got an unexpected keyword argument 'file_ids'
```

### PR DESCRIPTION
**Pull request by naingthet**
# Description

This PR addresses a bug with `OpenAIAssistantAgent` resulting from the transition from the `file_ids` kwarg to `attachments` kwarg when creating assistants. The present solution formats the existing `file_ids` into `attachments` objects, without specifying `tools` within each `attachment`, as this is optional ([see here](https://platform.openai.com/docs/api-reference/messages/createMessage#messages-createmessage-attachments)).

Another solution could be to add an `attachments` argument to `OpenAIAssistantAgent` methods. However, the present solution would be more seamless with any existing uses (i.e. it would not require any changes to any existing uses of this agent).

Fixes #12968

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [x] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

### CODE REVIEW

**Comment by naingthet** [comment]
After further inspection--I think this PR will work as a temporary fix, but the agent probably needs some refactoring to adopt the significant changes to how tools and files are passed in. The new Assistants API now has a `tool_resources` argument that divides file IDs (for code interpreter) and vector store IDs (for the new integrated vector stores). https://platform.openai.com/docs/api-reference/assistants/createAssistant

**Comment by logan-markewich** [comment]
Hmm, I tried running this but got `TypeError: Assistants.create() got an unexpected keyword argument 'attachments'`

I have `openai==1.26.0` installed. Looking at the type hints, I don't think `attachments` is a valid kwarg here 🤔

**Comment by naingthet** [comment]
Thanks for checking it out, will take another look. I don't think I set up my dev environment correctly...

**Review by logan-markewich — APPROVED** [review]

**Comment by logan-markewich** [comment]
@naingthet I tried running a few of our openai assistant notebooks, and ran into this:

```
Error code: 400 - {'error': {'message': "Invalid value: 'retrieval'. Supported values are: 'code_interpreter', 'function', and 'file_search'.", 'type': 'invalid_request_error', 'param': 'tools[0].type', 'code': 'invalid_value'}}
```

Or

```
AttributeError: 'Task' object has no attribute 'strip'
```

Seems like its still pretty unstable 😅 But lets merge this for now, and in another PR you or me or someone can make a complete revamp here

**Pull request merged**
